- board/can.h
- board/gpio.h
- lib/panda.py
- Fixes off-by-one error in can bus speed calculation, that was preventing single-wire GMLAN from working on my Chevy Volt gen 2.
- Instead of just replacing 0x001c002d with 0x001c002c, this PR makes it easier to understand, debug, and change the CAN speed configuration code, should someone need a different bus rate in the future.
- Enables sending/receiving extended addresses (majority of messages on single-wire GMLAN on my car).
> Single-wire GMLAN support

- board/Makefile
- board/build.mk
- board/early.c
- board/early.h
- board/main.c
Closes #4 
Removed inline keywords on all functions. 
Split early.h into a header and c file.
Updated Makefile rules to be more consistent.
> Remove inline keywords, cleaned up build.md, set compiler standard.

- board/build.mk
Use wildcard rule syntax to handle all c files in directory with a single rule.
> More consistent make rule for c files in 'board'.

- driver/.gitignore
- driver/Makefile
- driver/panda.c
- driver_test/Makefile
- driver_test/main.c
- driver_test/run.sh
First version of the Panda Kernel Driver. 
Works with all 3 CNA interfaces of the Panda. 
Passes workbench test of panda to panda communication.
> Kernel driver

- board/can.h
- board/main.c
- panda/__init__.py
- tests/loopback_test.py
Can bus numbers are 7 bit numbers with the 8th bit marking receipt busses (0x80,0x81,0x82 not 2,3,6).
Clear can forwarding by setting to 0xFF.
> Can bus numbers now sequential (0,1,2 not 0,1,4).

- board/main.c
Can loopback was merged while still called the function with the old parameters.
> Declaration of function changed in 'sane can ids'.

- .travis.yml
- boardesp/Makefile
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://travis-ci.org/gliptak/panda/builds/294507918 currently fails with:
```
esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -Iinclude/ -I. -I../ -mlongcalls -Iesp-open-sdk/ESP8266_NONOS_SDK_V1.5.4_16_05_20/driver_lib/include -std=c99 -DICACHE_FLASH "-DALLOW_DEBUG"   -c -o webserver.o webserver.c
webserver.c:14:28: fatal error: obj/gitversion.h: No such file or directory
#include "obj/gitversion.h"
^
compilation terminated.
make: *** [webserver.o] Error 1
```
Where does ```gitversion.h``` load from?
Thanks
> Add board and boardesp to Travis

- .travis.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
The build time improved some, but reviewing the logs I still see compiles.
Maybe https://github.com/pfalcon/esp-open-sdk could be asked to publish (pre-compiled) releases?
https://github.com/commaai/panda/pull/63
> Cache crosstool-NG for Travis

- drivers/linux/README.md
It took me a minute to figure out how to spin up the interface after installing the driver, so I added to the docs.
> updated linux driver docs

- board/drivers/usb.h
- tests/read_winusb_descriptors.py
`USB_WritePacket` couldn't handle the `len` parameter being greater than 127 and the WinUSB Extended Properties Feature Descriptor length is 142.
The way I read the reference manual, if you are not using interrupts you need to check `DTXFSTS` for room in the TX FIFO and wait for available space, so I added that in addition to a loop to send all the packets one at a time.
> fix sending WinUSB Extended Properties Feature Descriptor

- board/build.mk
With no optimization, Chevy Volt safety makes panda.bin larger than 32k and it no longer fits in a Panda.
> Enable optimization to reduce firmware size

- board/safety.h
- board/safety/safety_gm.h
Resets controls_allowed not only gas and brake, but on pressing regen paddle as well.
Radar configuration, dashboard status, and chime messages are always allowed through.
> Chevy Volt safety

- tests/can_printer.py
This fixes the below error I was running into:
```
opening device 148013800f51363038363036 0xddcc
connected
Traceback (most recent call last):
File "tests/can_printer.py", line 37, in <module>
can_printer()
File "tests/can_printer.py", line 31, in can_printer
for k,v in sorted(zip(msgs.keys(), map(lambda x: x[-1].encode("hex"), msgs.values()))):
File "tests/can_printer.py", line 31, in <lambda>
for k,v in sorted(zip(msgs.keys(), map(lambda x: x[-1].encode("hex"), msgs.values()))):
AttributeError: 'bytearray' object has no attribute 'encode'
```
> can_printer.py bytearray encode error

- README.md
I think it's better if user made scripts were linked to on a wiki page instead of PRs to the examples folder in this repo
> added link to wiki for user scripts

- board/drivers/can.h
- board/drivers/gmlan_alt.h
- board/main.c
This PR adds an alternate mode for the GMLAN output on the panda where it can be used as a general purpose output (set high or low). To accomplish this, a timer forces the GMLAN output low if every 15ms if the desired output is high to bypass the GMLAN transceiver hardware's 17ms timeout
```
gmlan_switch_init(0); //0 = timeout disabled; 1 = timeout enabled.
// With timeout enabled you need to call reset_gmlan_switch_timeout()
// faster than every 1s or the GPIO mode will be disabled
set_gmlan_digital_output(GMLAN_HIGH); //set output high
set_gmlan_digital_output(GMLAN_LOW); //set output low
```
> Add an alternate function to use GMLAN output on panda as a GPIO

- board/build.mk
fixes https://github.com/commaai/openpilot/issues/522
The sizes look fine:
```
make clean && make recover; ls -l obj/bootstub.panda.*
with this pull request (-Os and -lgcc)
8024 Feb  5 21:57 obj/bootstub.panda.bin
182460 Feb  5 21:57 obj/bootstub.panda.elf
60272 Feb  5 21:57 obj/bootstub.panda.o
original before the -Os commit (-O2 and no -lgcc)
8988 Feb  5 22:00 obj/bootstub.panda.bin
187596 Feb  5 22:00 obj/bootstub.panda.elf
68400 Feb  5 22:00 obj/bootstub.panda.o
```
However I'm not sure how to test bootstub beyond using it to flash a Panda and seeing if the Panda works.
Saw this fix suggested here: https://stackoverflow.com/questions/23410221/linking-libgcc-into-a-nostdlib-compilation
> add -lgcc flag to fix "undefined reference to __aeabi_llsr"

- tests/safety/test_chrysler.py
- tests/safety/trim_csv.py
I've found this super useful when working on the chrysler panda safety code.
In Cabana, download "Save Log" and then put it into the panda/tests/safety/ directory. Then run test.sh and it will fail if any of the transmitted messages are blocked by Panda's safety code.
Optionally use trim_csv.py to make your logs smaller.
> panda safety test that replays drives of saved CAN messages

- python/__init__.py
This might help figure out what is going on with panda flashing failures. It will raise a CalledProcessError and the stack will have the return code and the stdout and stderr from the subprocess.
> Capture make failure so it can be logged to sentry

- board/safety/safety_chrysler.h
This keeps the stock LKAS camera active so that we can copy data from its messages.
I'll open a PR in openpilot with code that uses this to support arbitrary Chrysler models, including 2019.
> chrysler: forward bus 0 to bus 2

- board/build.mk
Main.o and bootstub.o were missing headers (like recent power_saving.h). Generate them instead to guarantee makefile re-makes if any dependency is modified.
> generate dependencies and clean

- board/safety.h
- board/safety/safety_honda.h
- board/safety/safety_toyota.h
- tests/safety/libpandasafety_py.py
- tests/safety/test.c
- tests/safety/test_honda.py
- tests/safety/test_toyota.py
- Added cancellation on gas pressed for Toyota
- minor nomenclature change
- fix bug in regression test (honda hook was called instead of toyota hook in gas interceptor test)
- added a complete set of tests to cover for gas interceptor
- remove unused TOYOTA_NOLIMITS safety mode
> Toyota gas cancellation

- board/safety.h
- board/safety/safety_cadillac.h
- board/safety/safety_chrysler.h
- board/safety/safety_elm327.h
- board/safety/safety_gm.h
- board/safety/safety_gm_ascm.h
- board/safety/safety_hyundai.h
- board/safety/safety_subaru.h
- board/safety/safety_tesla.h
- board/safety/safety_toyota.h
Both operands of an operator in which the usual arithmetic conversions are performed shall have the same essential type category
> Misra 10.4 violations

- board/config.h
- board/drivers/usb.h
- board/main.c
- board/pedal/main.c
- board/safety.h
- board/safety/safety_cadillac.h
- boardesp/elm327.c
- boardesp/proxy.c
- boardesp/webserver.c
- drivers/windows/pandaJ2534DLL/MessageRx.h
- drivers/windows/pandaJ2534DLL/PandaJ2534Device.cpp
- python/esptool.py
- tests/elm_car_simulator.py
- tests/safety/test.c
Resolves some Misra violations, since `min` and `max` are also used in the def of a strcut.
> capitalize MIN and MAX macros

- board/drivers/gmlan_alt.h
Both operands of an operator in which the usual arithmetic conversions are performed shall have the same essential type category
> Misra 10.4: Both operands of an operator in which the usual arithmetic conversions are performed shall have the same essential type category

- board/drivers/can.h
- board/drivers/gmlan_alt.h
- board/main.c
Misra 17.7: The value returned by a function having non-void return type shall be used
> Propagate can_push errors

- board/safety.h
- board/safety/safety_mazda.h
Implement the safety limits.
Smarter forwarding:
Detect what msgs are sent by OP and drop corresponding CAM msgs
Detect if Stock CAM is connected
Detect if CAM is in hardware passthrough
Works  great With the DIY Mazda giraffe
Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>
> Add Mazda Safety

- board/config.h
- board/drivers/can.h
- board/drivers/uart.h
- board/drivers/usb.h
- board/main.c
- tests/misra/coverage_table
- tests/misra/suppressions.txt
- tests/misra/test_misra.sh
Updates to latest cppcheck commit and fixes the following rules:
```
10.4: Both operands of an operator in which the usual arithmetic conversions are performed shall have the same essential type category
18.4: The +, -, += and -= operators should not be applied to an expression of pointer type
```
Also adds coverage for a rule that had no violations:
```
17.2: Functions shall not call themselves, either directly or indirectly
```
> Misra update

- board/main.c
This makes sure that each time the last available characters are available to be sent when the usb command is used.
This results in the message length coming in to boardd only being 1 or 2 chars, not ruining the logic there.
> GPS UART fix until boardd is refactored

- board/boards/white.h
- board/drivers/harness.h
- board/main.c
- python/__init__.py
What was wrong:
- can based ignition would not trigger the interrupt on ignition line that changes the power save mode and set usb power mode to CDP.
- easy to trigger race conditions where EON changes the safety mode and re-enables some of the CAN lines after the ignition off interrupt is triggered. 
What is done:
- Move power save mode logic to boardd (openpilot). ON when car is ON, OFF when car is ON.
- Only set_power_save_state call in panda is when EON is disconnected: we already enter SILENT safety mode and now we also enter power saving mode, to ensure that if EON is disconnected while car is ON, panda won't remain in high consumption mode.
- enter CDP mode when (check_started) is True
- added usb command to change power save state
- added power save state to the health packet
- …
> Power saving refactor

- board/drivers/usb.h
Panda does not seem usable for many people on modern Windows; it won't enumerate at all. See for example #297. According to @gregjhogan on Discord, it looks like it broke last year in commit https://github.com/commaai/panda/commit/6dbd8c972ba2426ca43d176a1eee8cf7b304ee0a. This PR fixes the problem in a way that appears completely legal by USB spec.
The problem was happening on two machines here, one each on Windows 8.1 and Windows 10. USB enumeration fails with code 43, "a request for the USB BOS descriptor failed." Windows 10 just complained of a device I attached malfunctioning. Those versions of Windows are known to perform stronger validation on USB devices:
- https://techcommunity.microsoft.com/t5/Microsoft-USB-Blog/Why-does-my-USB-device-work-on-Windows-8-0-but-fail-on-Windows-8/ba-p …
> Fix USB device enumeration on Windows 8.1 and Windows 10

- examples/can_logger.py
Fix opening a csv file to python3 format, use built in .hex() function instead of binascii, and use f-strings instead of str() methods.
> Fix can_logger.py to run correctly on python3

- drivers/windows/ECUsim CLI/ECUsim CLI.vcxproj
- drivers/windows/ECUsim DLL/ECUsim DLL.vcxproj
- drivers/windows/README.md
- drivers/windows/panda/panda.vcxproj
- drivers/windows/pandaJ2534DLL Test/pandaJ2534DLL Test.vcxproj
- drivers/windows/pandaJ2534DLL/MessageRx.h
- drivers/windows/pandaJ2534DLL/PandaJ2534Device.cpp
- drivers/windows/pandaJ2534DLL/pandaJ2534DLL.vcxproj
- drivers/windows/panda_playground/panda_playground.vcxproj
- drivers/windows/redist/vscruntimeinfo.nsh.sample
J2534 DLL needs to be re-compiled after https://github.com/commaai/panda/commit/70219d7bb2d9870becd9d78f2a7b5eac30babbd3#diff-6f161adc7ea629a143f5034c996be85b changed `SAFETY_ALLOUTPUT` constant
> update J2534 driver for new SAFETY_ALLOUTPUT value

- drivers/windows/README.md
- drivers/windows/panda_shared/panda.h
HDS for pre-2017 vehicles won't open because it can't read the car battery voltage due to https://github.com/commaai/panda/pull/391 changing the order of the health packet type def
> update J2534 driver for new health data structure

- board/drivers/gmlan_alt.h
Fix for issue #416 
Debug console didn't work anymore since it was flooded with 'invalid gmlan' message. Also triggered temp fault since that interrupt was running at full speed
> Fixed GMLAN interrupts when used in Tesla safety

- board/safety/safety_honda.h
for some Honda models when OP is engaged, stock AEB will activate in unexpected circumstances, such as when there are 2 lane highways when driving on a curve with opposing traffic.  When this occurs the car may brake unexpectedly (Honda Civic) or loss of gas pedal function may occur for a few seconds (Honda Pilot).  This PR disables the stock Honda AEB in the Panda code gated under unsafe_mode.
> disable stock honda AEB in unsafe mode

- board/main.c
- tests/safety/common.py
- tests/safety/libpandasafety_py.py
- tests/safety/test.c
Required to validate changes in Panda safety operation after use of the "unsafe mode" flag.
When this lands I have the appropriate changes and tests for "no disengage on gas" for both Volkswagen MQB and PQ.
> Support code for unsafe mode unit tests

- board/safety/safety_volkswagen.h
- tests/safety/test.c
- tests/safety/test_volkswagen_mqb.py
- tests/safety/test_volkswagen_pq.py
Implement `UNSAFE_DISABLE_DISENGAGE_ON_GAS` for both Volkswagen MQB and PQ, with tests. Also fix a test compile warning (not VW specific) that's been annoying me for a while.
Regarding the other unsafe_mode flags:
`UNSAFE_DISABLE_STOCK_AEB`, N/A because Volkswagen never needs to disable stock FCW/AEB
`UNSAFE_ENABLE_WEAK_STEERING_WHILE_NOT_ENGAGED`, might do this at some point
`UNSAFE_RAISE_LONGITUDINAL_LIMITS_TO_ISO_MAX`, N/A until we take long control
> Unsafe mode gas disengage for VW MQB and PQ

- python/__init__.py
Detaching all kernels before attempting to claim the usb
> Fixing libusb busy error

- board/drivers/can.h
- board/drivers/usb.h
- board/main.c
- board/pedal/main.c
- board/spi_flasher.h
- python/__init__.py
- tests/automated/7_can_loopback.py
- tests/bulk_write_test.py
It is easy to overflow the TX buffer when sending a large number of messages rapidly. When sending UDS messages you don't want anything to get silently dropped. This change causes the client to pause (leave NAK active) until there is enough room in the TX buffer to process the next USB data packet. Not sure if this is desirable in all scenarios, or even if this is the right way to handle the situation, but it does seem to work.
> TX message guaranteed delivery

- board/drivers/llcan.h
- board/safety/safety_toyota.h
- tests/safety/test_toyota.py
While refactoring the safety tests to use the can packer, I noticed that some toyota models (like prius) aren't included in the gas press check since they didn't have the `0x2c1` signal. This new signal is in the `PCM_CRUISE` message, so this should work for all toyota.
Ideally, there should be a test that tests each model and checks that panda safety and CarState agree to catch things like this.
Closes #404
> toyota: use universal gas pressed bit

- board/safety/safety_chrysler.h
- tests/safety/test_chrysler.py
The Chrysler TX hook only allows spoofing of cancel, but since it only checked the first byte, it missed the `ACC_FOLLOW_INC` signal. The test also didn't check for this.
https://github.com/commaai/opendbc/blob/master/chrysler_pacifica_2017_hybrid.dbc#L208
> Chrysler: fix missing button signal on TX

- python/__init__.py
Only on debug builds you can go straight into bootloader.
> Panda recover should go through bootstub first

- examples/can_unique.py
also fix python3 issue where open() was in binary mode, but we want text mode.
> add support to can_unique.py for Cabana CSV format.

- board/build.mk
Title says it all. This helped at least one user get unstuck from Panda refusing to accept DEBUG signed firmware by flashing it via DFU from the command line. Original update process fix taken from f07a6ee.
This fix may help users experiencing #449.
> Match Panda DFU entry fix in "make recover" process

- tests/safety/test_chrysler.py
- tests/safety/test_volkswagen_pq.py
Neither use the can packer yet, but I wanted to get this in before some other refactors. Once I add the chrysler checksum to the can packer, I'll submit another PR. Same for when a Volkswagen PQ dbc gets upstreamed.
> Safety Test Refactor: Chrysler and Volkswagen PQ

- board/safety/safety_subaru.h
- tests/safety/test_subaru.py
I was hesitant to change the legacy scaling for driver torque since the [DBC](https://github.com/commaai/opendbc/blob/master/subaru_outback_2015_eyesight.dbc#L280) has a wildly different factor.
@bugsy924 can you verify the scaling factor for driver torque for legacy? or maybe the DBC needs to be updated?
> Subaru: fix steer torque scaling

- python/__init__.py
On Windows, setAutoDetachKernelDriver is not supported ([libusb docs](http://libusb.sourceforge.net/api-1.0/group__libusb__dev.html#ga5e0cc1d666097e915748593effdc634a)) and causes libusb to get stuck (simple try-catch is not working). This prevents any issues when running both at native windows python and cygwined python...
How it looks without fix (running can_logger.py from examples):
```
Trying to connect to Panda over USB...
opening device asd  450033000851363038363036 0xddcc
exception LIBUSB_ERROR_NOT_SUPPORTED [-12]
Traceback (most recent call last):
File "./git/panda/python/__init__.py", line 190, in connect
self._handle.setAutoDetachKernelDriver(True)
File "/usr/lib/python3.6/site-packages/usb1/__init__.py", line 1346, in setAutoDetachKernelDriver
self.__handle, bool(enable),
File …
```
> Fix python library on Windows

- board/boards/black.h
- board/boards/uno.h
Both Black Panda and Uno transceiver enabled code needed to be updated to match ODB-C orientation. Otherwise it only works in one orientation.
Uno needed to be updated to leave the transceiver mapped to BUS 0 enabled while sleeping to listen for CAN based ignition.
> Fix CAN Ignition for Black Panda and Uno

- board/drivers/llcan.h
- board/safety/safety_honda.h
- tests/safety/libpandasafety_py.py
- tests/safety/test.c
- tests/safety/test_honda.py
> honda bosch longitudinal safety

- board/safety.h
- board/safety/safety_chrysler.h
- board/safety/safety_gm.h
- board/safety/safety_honda.h
- board/safety/safety_hyundai.h
- board/safety/safety_nissan.h
- board/safety/safety_subaru.h
- board/safety/safety_toyota.h
- board/safety/safety_volkswagen.h
- board/safety_declarations.h
Needed to cleanly add the gas signal to the RX checks for hyundai EVs, which doesn't have a counter
Changes:
* check_checksum, max_counter, and expected_timestep are now properties of the individual can message, not all the allowed messages for an RX check
* before when multiple msgs were allowed, either could update the RX check struct, however now it only uses the first one it sees for the subsequent checks
> Refactor addr check

- board/safety/safety_nissan.h
ACC wasn't being cancelled when gas was pressed
> Fix length of 0x20b in NISSAN_TX_MSGS

- .github/workflows/test.yaml
- Dockerfile.panda
- tests/misra/test_misra.sh
moves the cppcheck build to the docker file so that it gets cached, misra test now takes 2.5 minutes down from 4.5
> Speed up misra test in CI

- board/boards/uno.h
- board/drivers/usb.h
- board/main.c
On some devices, the suspend condition sometimes false-triggers as enumerated when the host is not connected due to noise on the USB lines. Trying to fix by checking if we actually rx the SOF packets (1/ms)
> USB enumeration detection fix

- board/boards/common.h
Uno sometimes identifies as Dos. Suspecting that the detection line is not pulled high long enough to generate a logical 1.
Needs to be tested.
> WIP: Improve board detection stability

- board/safety/safety_nissan.h
`generic_rx_checks()` was creating a harness error as `0x169` was being sent on bus 2 (from ADAS) and `(addr == 0x169)` would return true in this case
> Bugfix: Fix harness error when starting car

- README.md
Several safety modes are available only with ALLOW_DEBUG flag. This is not noted in docs and no error message will warn you in case of setting non-existing or disabled safety mode.
> Readme.md edit - Warning of disabled safety modes

- Dockerfile.panda
- tests/safety/test_subaru.py
Use generated Subaru global dbc in safety test, related to https://github.com/commaai/opendbc/pull/277
> Change Subaru safety test to use generated dbc

- board/boards/uno.h
Subtle bug, triggered by PR #611.
This should reduce the power draw of some comma twos by more than a watt when the phone is powered off.
> Fix C2 power draw

- python/uds.py
**Prep for Volkswagen MQB FPv2**
Add support for UDS diagnostic queries to come back with non-standard response address offsets. For VW MQB, the engine and transmission respond at the conventional offset of 0x8, but most other controllers use 0x6A.
**Verification**
Worked in my old FPv2 mockup branch: https://github.com/commaai/openpilot/pull/1427
> VW MQB: Add UDS library support for variable response offsets

- board/safety/safety_hyundai.h
- tests/safety/test_hyundai.py
It was pure coincidence that this checksum ever worked.  Makes me wonder if there are any cars that openpilot doesn't work because of this bug.
This is stacked on top of https://github.com/commaai/panda/pull/622 (<- please merge first)
Good example of how adding up the bytes is a horrible checksum!
> hyundai: TCS13 checksum

- board/gpio.h
This fixes #613 
The `early()` function runs twice, once before the bootstub and once between bootstub and application code. The bootstub configures and enables interrupts. The `early()` function then changes the ISR table base. After the `early()` call is done it goes back into the startup code which clears out the interrupt handler table in `interrupts.h`. This table is later initialized in application code, after which interrupts can be enable again. During all of this you don't want interrupts to be enabled or it can cause all kind of undefined behavior. On the first run this is not a problem since no actual interrupts are configured yet, but on the second run there is still leftover configuration from the bootstub.
I'm still not _exactly_ sure why this is only a problem when you …
> Disable interrupts in early()

- README.md
- drivers/windows/README.md
1/2 fixing up docs primarily urls (2/2 is https://github.com/commaai/openpilot/pull/21309)
> Fixup broken links and remove references to now-defunct eon gold dashcam devkit

- examples/query_fw_versions.py
**Bug fixes:**
* Take Panda out of powersave mode so the OBD bus CAN transceiver actually works
**New features:**
* Support querying a single address instead of the entire address range
* Switch to best available diagnostic session without security access
* Support queries for all standard UDS data identifiers
* Support queries for nonstandard vehicle manufacturer/supplier reserved identifier ranges
* Support German Engineered™ ISO-TP receive offsets
**Known issues:**
* Timeout isn't long enough for certain *really* long ISO-TP replies, which ends up throwing an assert deep in the UDS library when the reply for a previous query is still arriving when we start the next. Timeout would have to be made absurdly longer, or the UDS library assert needs to become a handle-able exception, or the …
> UDS fingerprinting development tool updates

- board/boards/black.h
- board/boards/dos.h
- board/boards/uno.h
- board/bootstub_declarations.h
- board/drivers/can.h
- board/main_declarations.h
Remove can_set_obd() from can.h
It was replaced by local to boards set_can_mode()
It got called only when board gets initialized.
> Remove can_set_obd

- board/drivers/usb.h
- board/stm32fx/stm32fx_config.h
Can't be done as a const while keeping pretty as it will violate MISRA rule 20.1
> Deprecate variable bcdDevice in usb.h

- python/__init__.py
- python/dfu.py
- tests/automated/3_usb_to_can.py
legacy mode with bcdDevice 0x22 was used for NEO and STM32F2 (had only two CANs)
> Deprecate bcdDevice and legacy mode from panda lib and tests

- board/drivers/usb.h
We will use bcdDevice to detect board type without the need to connect to board.
> set bcdDevice to hardware type

- board/safety/safety_honda.h
- tests/safety/common.py
- tests/safety/test_honda.py
- tests/safety_replay/helpers.py
Honda has started using some extended IDs on 2021+ Bosch Hondas on the private CAN. They have also modified how the checksum is being calculated for the new messages (based on the two IDs that we're dealing with; 0x33DA and 0x33DB). The method is the same as before, but they do additional math if the ID is extended.
I know the extended IDs aren't being checked in panda, but it's there if needed. We run the same checksum changes in opendbc with success.
Some message examples:
```
- Original -
0x33d: 0000104000
0x33d: 000010401f
0x33d: 000010402e
0x33d: 000010403d
- Modified sum -
0x33da: 0000104009
0x33da: 0000104018
0x33da: 0000104027
0x33da: 0000104036
0x33db: 0000104000000008
0x33db: 0000104000000017
0x33db: 0000104000000026
0x33db: 0000104000000035
```
> Honda Bosch: Support extended LKAS_HUD IDs

- board/safety/safety_volkswagen.h
- tests/safety/test_volkswagen_mqb.py
- tests/safety/test_volkswagen_pq.py
Panda isn't currently handling `controls_allowed` for Volkswagen quite the same as other ports. We're only supposed to enter controls on rising edge of ACC engagement, but right now we're considering controls allowed whenever ACC is engaged. As far as I can tell, the real-world impact of this is pretty low, but this should be fixed anyway.
First commit will revert the overridden tests that allowed this to go undetected, reverting to the common inherited tests that look for this behavior. Second commit will fix the safety to pass the new tests.
Planning to hold this in draft for a short time, while I make sure this is working as-planned for community users.
> VW MQB and PQ: Fix controls entry conditions and tests

- board/drivers/bxcan.h
- board/drivers/can_common.h
- board/drivers/fdcan.h
In the can TX interrupt it is checked if there is enough space in the buffers to allow more USB packets to come in. However, when the car is shutting down it's possible a bunch of messages that have to be sent to the camera are never ACKed and fill up the buffer. All further USB transfers would be blocked since the buffers are full, and the TX interrupt will never fire again.
If on following car startup you try to send messages from ELM or ALL_OUTPUT mode they would fail to send due the USB stack still thinking the buffers are full. As soon as you switch to a car safety mode with a fwd hook the CAN TX interrupt starts firing again solving the issue.
This PR adds the same check as in the CAN TX interrupt to the can buffer clear function (which get's called on safety mode switch) to solve …
> Try resuming outep3 on can buffer clear

- python/flash_release.py
The variable "version" extract from the zip file has a redundant new line, which causes assert error when flash release. It must be strip before assert.
> Fix assert error when flash release

- board/SConscript
- board/bootstub_declarations.h
- board/drivers/can_common.h
- board/drivers/uart.h
- board/drivers/usb.h
- board/main.c
- board/main_declarations.h
- board/pedal/main.c
- board/pedal/main_declarations.h
support enabling debug flags when flashing
```sh
DEBUG=1 ./flash.sh
```
and improve debug console output
```
** blink rx:000009e5/00000a1d  tx1:000000ce/000000cb  tx2:00000000/00000000  tx3:00000000/00000000
** blink rx:00000983/00000a30  tx1:00000033/0000002f  tx2:00000000/00000000  tx3:00000000/00000000
** blink rx:00000a43/00000a53  tx1:000000a8/000000a7  tx2:00000000/00000000  tx3:00000000/00000000
** blink rx:000009e3/00000a74  tx1:0000001b/00000017  tx2:00000000/00000000  tx3:00000000/00000000
can_push to can_tx1_q failed!
can_push to can_tx1_q failed!
** blink rx:00000a80/00000a97  tx1:00000090/00000071  tx2:00000000/00000000  tx3:00000000/00000000
** blink rx:00000a3f/00000ab2  tx1:000000fd/000000f9  tx2:00000000/00000000  tx3:00000000/00000000
```
> expose debug flags and improve debug console output

- board/safety/safety_volkswagen.h
- tests/safety/test_volkswagen_pq.py
*BREMSE_3* message is not present on *NSF* platform (VW e-up).
Change the use of *BREMSE_3* to *BREMSE_1* for reading the speed and setting up `vehicle_moving` flag accordingly.
This was checked together with @jyoung8607 and should work for all *PQ* since "all PQ including NSF should have that speed".
> VW PQ: use Bremse_3 for ego speed

- board/safety/safety_subaru.h
- tests/safety/test_subaru.py
Use alternative Brake_Status Brake signal instead of Brake_Pedal Brake_Pedal signal. Fixes ACC disengage while braking issue for various newer models (https://github.com/martinl/openpilot/issues/27, https://github.com/commaai/openpilot/pull/20866)
Openpilot PR https://github.com/commaai/openpilot/pull/21012
> Subaru Global: use better brake pressed signal

- board/get_sdk_mac.sh
updated script after following url https://raw.githubusercontent.com/Homebrew/install/master/install
that url returns the following indication:
STDERR.print <<EOS
Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
EOS
Kernel.exec "/bin/bash", "-c", '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
> updated: ruby homebrew installer deprecated.

- board/drivers/usb.h
- board/main.c
- python/__init__.py
- tests/automated/4_can_loopback.py
I noticed TX messages getting dropped when sending large amounts of CAN messages really fast with a timeout specified (and USB NAKs are needed).  I am sure I have the max number of messages per USB packet correct, so somehow it seems like a second packet sneaks in when we want to start NAKing but I am failing to see how.  I tried adding `ENTER_CRITICAL()` and `EXIT_CRITICAL()` around `usb_irqhandler` but it doesn't help, so I am not sure how this happens.  Since I don't understand what is going on, I am worried that maybe more than one extra USB packets could somehow sneak in and this isn't a real fix.
> Fix bulk transfer dropping messages sometimes

- board/safety/safety_subaru.h
subaru_l_rx_checks was referencing subaru_addr_checks instead of subaru_l_addr_checks
> Fix subaru legacy rx check

- tests/automated/1_program.py
- tests/automated/3_usb_to_can.py
- tests/automated/4_can_loopback.py
Recover test must go before flash test for better stability(to flash main and bootstub firmwares first)
Also 750kbps speed is not used by CAN/CAN FD and prevents to reach both 2 and 5 Mbps with CAN FD because of time quanta.
> Improve tests

- board/safety.h
- board/safety/safety_defaults.h
This safety mode opens relay and forwards messages from bus 0 to 2 and from bus 2 to 0. That way we can know for sure which messages were sent by camera. 
It is only allowed when compiled with DEBUG set to true.
> Add passthrough safety mode

- board/drivers/can_common.h
- board/drivers/fdcan.h
- board/main.c
- python/__init__.py
Enable CAN FD support.
CAN FD enabled if can_data_speed is set. Also BRS enabled if can_data_speed is higher than can_speed.
can_data_speed must be set after can_speed (and that's seems logical)
P.S.: Based on #739 , testing.
> Enable CAN FD support

- board/get_sdk.sh
dfu-util package missing from get_sdk.sh. Flash and recover tasks fail without it.
Package already included in the mac version of the script, and is also included in the dockerfile
Also updated python-pip to python3-pip and added the '-y' flag to apt-get.
> board/get_sdk.sh: add dfu-util and python3-pip

- tests/safety/common.py
- tests/safety/test_volkswagen_mqb.py
In preparation for adding openpilot longitudinal control tests, null-effect refactor the MQB safety tests into a common base class and layer stock longitudinal on top. While here, add some helpful instrumentation to the common tests.
The full OP long PR will come right behind this, but there are problems with `test_tx_hook_on_wrong_safety_mode()` yet to solve, and I thought it best to do so in smaller pieces.
> VW MQB: Prep for longitudinal safety

- board/can_definitions.h
- board/drivers/bxcan.h
- board/drivers/can_common.h
- board/drivers/fdcan.h
- board/drivers/gmlan_alt.h
- board/safety/safety_chrysler.h
- board/safety/safety_ford.h
- board/safety/safety_gm.h
- board/safety/safety_honda.h
- board/safety/safety_hyundai.h
- board/safety/safety_mazda.h
- board/safety/safety_nissan.h
- board/safety/safety_subaru.h
- board/safety/safety_tesla.h
- board/safety/safety_toyota.h
- board/safety/safety_volkswagen.h
- board/safety_declarations.h
- board/usb_protocol.h
- tests/misra/suppressions.txt
Fix MISRA violations 10.1 and 10.4 that were suppressed before. Total 200+ violations, most of them were in safety code. I am still not happy with code cleanliness, will continue in following PRs. (All bitwise and shift operations should have unsigned operands only)
> Fix MISRA violations 10.1 and 10.4

- board/early_init.h
- board/stm32h7/clock.h
Makes USB more stable while switching between app and bootloader, also should decrease power draw a bit.
> H7: Move from PLL3Q to HSI48 for USB FS

- board/safety/safety_gm.h
- tests/safety/test_gm.py
Updated GM safety code and tests to use AcceleratorPedal2 (452) rather than AcceleratorPedal (417) for detecting gas pressed.
The values for the pedal in the two messages are identical, and AcceleratorPedal is not present on the 2020 Silverado. 452 is present in all the existing fingerprints that also contain 417, and they were* both required in OP.
Corresponds with OP PR https://github.com/commaai/openpilot/pull/23280
> GM Switch to AcceleratorPedal2 for pedal pressed

- requirements.txt
- setup.py
1.6.6 seems to be broken.
```
Collecting libusb1==1.6.6
Using cached libusb1-1.6.6.tar.gz (56 kB)
Preparing metadata (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/willem/.local/share/virtualenvs/pq-flasher-VXrEoMdV/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ivmtemtr/libusb1_6b45ebf3a98445a5ab9f2af595377054/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ivmtemtr/libusb1_6b45ebf3a98445a5ab9f2af595377054/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base …
```
> Update libusb to 2.0.1

- tests/safety/common.py
* Smarter coverage ranges for `test_relay_malfunction`, `test_fwd_hook`, and `test_spam_can_buses`
* Ensure that any new TX_MSGS outside the coverage range will fail testing until the range is expanded
* Minor consistency cleanup
Resolves #823
> Better CAN address range scanning

- board/drivers/can_common.h
Linked to issue https://github.com/commaai/openpilot/issues/23645
Verify on these cars:
Thanks to a route provided by @twilsonco (`e69bcbc2c84de4d2|2022-02-02--17-03-51`), this shows the preconditioning feature of a Chevy Volt being used, and has the old signal at 1 and the new signal at 0. This is the reason there's so many mismatches in the Chevy Volt comparisons, they're all false positives. Plot: https://imgur.com/a/Ed2MHWk
A few plots: https://imgur.com/a/PEYtWm5
Checked data:
```
Platform: GMC ACADIA DENALI 2018
Checked 1 unique dongles, 53 unique routes, and 593 segments
Mismatches: 23 frames, 0 segments (any frame)
---
Platform: CADILLAC ESCALADE ESV 2016
Checked 10 unique dongles, 116 unique routes, and 617 segments
Mismatches: 0 frames, 0 segments (any frame)
---
Platform: …
```
> GM ignition: remove signal with noise and false positives

- board/safety/safety_honda.h
In openpilot we now set brake pressed if either (brake pressed (as before)), **or** (brake switch is 1 for two frames in a row and it's being updated).
> Honda: match openpilot brake pressed check

- board/stm32h7/peripherals.h
Was not really used, but should have been enabled.
> H7 bugfix: enable SYSCFG peripheral clock

- board/drivers/bxcan.h
- board/drivers/fdcan.h
- board/stm32h7/llfdcan.h
There are two SAE specifications for CAN FD vehicle applications:
SAE J2284-4 document specifies a bus-line network running at 2 Mbit/s
SAE J2284-5 document specifies a point-to-point communication running at 5 Mbit/s (for diagnostic tools)
In both cases nominal(arbitration) speed is always 500Kbit/s
This PR adjusts bit timing values(and prescaler) to be in compliance with SAE specs.
> CAN FD: adjust bit timing settings to SAE specifications J2284-4 and J2284-5

- tests/automated/3_usb_to_can.py
- tests/automated/4_can_loopback.py
For singe speed tests we care only about 500Kbit/s (instead of 250)
For multiple speeds tests - larger speeds list to check for possible clock/prescaler problem.
> HITL tests: change testing speeds

- board/main.c
Helps when usb_power_mode was not set to client before shutdown of a C2 device.
> Bootkick on ignition if USB isn't enumerated

- board/drivers/can_common.h
- board/drivers/fdcan.h
- tests/canfd/test_ci_canfd.py
If panda got CAN FD message on a bus - it will switch automatically to CAN FD mode on send on this bus.
Closes #795
> Red Panda: enable auto switching to CAN FD with BRS

- Dockerfile.panda
- tests/safety/test_toyota.py
1. Jinja2 updated in the opendbc
2. EPS scale factor for Toyota was moved from opendbc to openpilot
> Docker: bump openpilot and fix Toyota EPS scale factor for test

- board/safety/safety_honda.h
- tests/safety/test_honda.py
The Honda safety now matches the behavior in openpilot and the stock system. This should also prevent mismatches between openpilot and panda.
> Honda: enter controls on falling edge of button presses

- board/safety/safety_tesla.h
- tests/safety/test_tesla.py
@robbederks any reason IDLE is also allowed? Seems openpilot only sends FWD. https://github.com/commaai/openpilot/blob/3d8537ab23197a383fd1dd7082329ddee1acfdb7/selfdrive/car/tesla/carcontroller.py#L56
> Tesla: only allow cancel button

- tests/safety/common.py
- tests/safety/test_honda.py
We were calling `common.InterceptorSafetyTest.setUpClass()` from a Honda test, however its `setUpClass` checks if the class name is itself and if so, then skip the test. However, when calling from a child `cls.__name__` was always the parent, so it just skipped those tests.
> Honda: fix missing interceptor tests

- tests/safety/common.py
- tests/safety/libpandasafety_py.py
- tests/safety/test_chrysler.py
- tests/safety/test_gm.py
- tests/safety/test_honda.py
- tests/safety/test_hyundai.py
- tests/safety/test_mazda.py
- tests/safety/test_nissan.py
- tests/safety/test_subaru.py
- tests/safety/test_subaru_legacy.py
- tests/safety/test_tesla.py
- tests/safety/test_toyota.py
- tests/safety/test_volkswagen_mqb.py
- tests/safety/test_volkswagen_pq.py
When reviewing the safety code, every time I looked at these messages it took some mental brain power to remember what the messages were for (user or command). Adding user made it fairly obvious
Renamed `_brake_msg` to `_user_brake_msg`, and `_gas_msg` to `_user_gas_msg`
> safety tests: rename gas/brake message functions

- board/boards/dos.h
- board/stm32fx/clock_source.h
This gets rid of the need for interrupt handling to generate the 20Hz camera signals.
Should improve the timing consistency, and should also limit the risk of interrupt starvation limiting the camera framerate.
> Dos: PWM based camera signals

- board/safety/safety_gm.h
Stock GM ACC keeps the active bit set (`GasRegenCmdActive`) when the user is overriding with gas, however with the addition of `longitudinal_allowed`, panda would always block these messages until a fault occurs.
Might need to use `controls_allowed` instead, as if we disengage on accelerator, we also won't allow the apply bit, which some users report causes faults as well. Will test
> GM: allow active regen bit when gas is pressed

- board/safety/safety_honda.h
- tests/safety/test_honda.py
If the panda interceptor threshold for gas pressed is higher than openpilot and if we're in between the thresholds, then in the pre-enable state, it is possible for the signal to fall below the panda threshold (so gas not pressed), then rise above the panda threshold (causing a rising edge of gas pressed). `controls_allowed` then gets set to 0, all while openpilot thinks the gas is pressed and is still in the pre-enabled state, then when the gas is released for openpilot we try to send messages and we get a controlsMismatch event.
> Honda: fix interceptor pressed mismatch

- board/safety.h
- board/safety_declarations.h
Size was changed in this commit, but comments never updated: https://github.com/commaai/panda/commit/bf70f5159649a581a023e0c271ea4df53eacc2e9
> sample_t: fixup comments

- README.md
Another gotcha as users may think that adding panda udev rules for panda also covers the panda jungle. Not adding the rules and running `can_replay.py` results in a hang with no error, which may confuse users.
> Note about panda jungle udev rules

- board/safety/safety_hyundai.h
- tests/safety/test_hyundai.py
This fixes an incorrect signal, always looking at `FCA_CmdAct` instead of `FCA_CmdAct`
> Hyundai: use GET_BIT and fix safety on incorrect bits

- board/safety/safety_toyota.h
- tests/safety/test_toyota.py
we have toyota_stock_longitudinal in safety_toyota.h
can we not block 0x343 if toyota_stock_longitudinal is set to true?
> Toyota: forward ACC messages if stock longitudinal

- board/safety/safety_toyota.h
- tests/safety/common.py
- tests/safety/test_chrysler.py
- tests/safety/test_gm.py
- tests/safety/test_hyundai.py
- tests/safety/test_mazda.py
- tests/safety/test_subaru.py
- tests/safety/test_subaru_legacy.py
- tests/safety/test_toyota.py
We could previously ramp up while the bit is 0 and then set to 1 and effectively bypass the openpilot and panda torque rate limits (although not too much as the max torque would be imposed to 350 away from the current due to the torque blending)
> Toyota: check STEER_REQUEST bit

- board/safety/safety_hyundai.h
- tests/safety/test_hyundai.py
You can wind up torque with the bit set to 0, then set to 1 to effectively bypass the panda torque rate limits. Seems to be around 2-4 frames of the mismatch before car faults?
Similar to PR: https://github.com/commaai/panda/pull/940/files
Todo:
> Hyundai: check CF_Lkas_ActToi bit

- tests/safety/common.py
- tests/safety/test_chrysler.py
- tests/safety/test_toyota.py
Just creates the classes to prepare for using them. Switch to `MotorTorqueSteeringSafetyTest` for Toyota and Chrysler
> safety tests: create classes for common torque steering tests

- board/safety/safety_mazda.h
- tests/safety/test_mazda.py
In openpilot, the max steer is only 800 units, but in panda we were allowing up to 2048 with a super high realtime allowance (allowed 800 torque in 0.2 seconds and 2048 torque in 0.55 seconds, while the rate up limit only allowed reaching 800 torque in 0.8 seconds).
Mazda safety changes:
- Runs all driver torque tests
- Change max torque constant to openpilot's
- Lower realtime delta limits to be 20% higher than max rate up
> Mazda: fix steering safety and add tests

- tests/safety/common.py
With #905 we were given a much nicer way to handle message counters in the safety test CAN packer, which should enable a nice future red diff for the Volkswagen tests among others. Since that PR, the car safety CI test has been passing, but it's also been spamming "COUNTER not defined" to console.
This traced back to a Toyota wheel speed message without a counter, but the Toyota test would run fine in isolation. The problem traced further back to the new CANPackerPanda leaking counter state between packer instances. This PR should fix it.
```
Testing HW_TYPE: 0
COUNTER not defined
COUNTER not defined
COUNTER not defined
COUNTER not defined
COUNTER not defined
COUNTER not defined
COUNTER not defined
COUNTER not defined
COUNTER not defined
COUNTER not defined
COUNTER not defined
COUNTER not …
```
> fix CANPackerPanda counter state init

- board/safety/safety_honda.h
Fixes a bug uncovered by https://github.com/commaai/panda/pull/874. We get quite a few messages from bus 2 where the first byte is 0xff for SCM_BUTTONS, we got unlucky as it parses out to 7 and considering buttons with no past didn't make this an issue (7 is not a recognized button) before. But now it's pretty much always guaranteed the last button is 7, so neither set or resume, causing controls_allowed never to rise.
This is a Bosch Civic: https://user-images.githubusercontent.com/25857203/172751996-27a04991-9232-4591-bdf1-70e13b5c409e.png
What panda sees: https://user-images.githubusercontent.com/25857203/172752445-56369f9e-712b-404a-8d62-3ddf91678646.png
Checked a Honda CR-V (Nidec), didn't have the button message on 0x1A6 on any other bus in normal operation, so only a bosch problem …
> Honda Bosch: consider correct bus for buttons

- tests/safety_replay/replay_drive.py
- tests/safety_replay/test_safety_replay.py
A new Civic 2022 route had no disengage on gas enabled so it was blocking a bunch of messages. This adds support for alternative experiences to safety replay
> safety replay: set alternative experience

- Dockerfile.panda
For cases where you need to merge a new signal to opendbc, however you can't bump opendbc on openpilot master until the panda PR is ready and tests pass. Previously you needed to make a second commit in panda to bump openpilot once it was merged (with failing panda tests).
> Dockerfile: pin opendbc commit

- board/main_declarations.h
- board/safety.h
- board/safety/safety_hyundai_hda2.h
- board/safety_declarations.h
Here's an example from the field. This particularly happens to affect Honda Nidec vehicles because unlike most PCM cruise cars, they don't disable controls_allowed on the falling edge of cruise to allow for braking down to a stop.
> safety: fix race condition in engagement heartbeat

- board/safety/safety_body.h
was bad idea to check length on msgs 0x*50, also don't need 0x7 anymore
> body: tx safety checks

- python/__init__.py
- python/config.py
- tests/pedal/enter_canloader.py
The latest panda commit in openpilot pushed the binary size (49460 bytes) just over the fixed 3 0x4000 pages (49152 bytes) it [erases before flashing](https://github.com/commaai/panda/blob/8b26ce940f8193012ede411fa55ed30e2c34c536/python/__init__.py#L300), which causes the check in the bootloader to fail.
> Dynamic sector erase

- board/safety.h
- board/safety/safety_chrysler.h
- board/safety/safety_ford.h
- board/safety/safety_mazda.h
- board/safety/safety_nissan.h
- board/safety/safety_subaru.h
- board/safety/safety_subaru_legacy.h
- board/safety/safety_tesla.h
- board/safety/safety_toyota.h
- board/safety/safety_volkswagen_mqb.h
- board/safety/safety_volkswagen_pq.h
- board/safety_declarations.h
On the way to making the safety modes more like openpilot (parsers), per recent conversation. Reducing the setting of controls_allowed in each car-specific mode also seems like a good move.
Hyundai and Honda add special logic to this check, so those aren't moved over yet.
> safety: common cruise checks

- board/main.c
With CAN-based ignition, it's possible that the panda wakes up from deep sleep after the CAN IRQ, but immediately goes back to sleep since `ignition_can` has not been set yet. This PR ensures minimum uptime to not allow that to happen.
> Minimum uptime for deep sleep

- board/main.c
- board/main_declarations.h
If the panda is in a multi-panda setup, it's possible that it will never see an ignition signal.
In this case, waking up from deep sleep is impossible, so let's just not enter it in the first place.
> Only allow deep sleep if there's been ignition before

- drivers/linux/README.md
This will make it consistent w/ the main `README.md`
> README: remove backtick typo

- examples/can_bit_transition.py
- examples/can_unique.py
> Update example scripts to support canfd

- board/safety/safety_elm327.h
Tesla has most ECUs in the 0x600-0x700 range, so we need to add this range to allow queries
> Add the 0x600 range for UDS messages

- python/uds.py
Adds a `setup_only` argument to `IsoTpMessage.send()` so that if the user wants to set up an `IsoTpMessage` to receive data after another `IsoTpMessage` sends a query, that is now possible (sending on a functional addr, and finishing communication on a physical addr for example).
> IsoTpMessage.send: setup_only argument

- board/safety/safety_hyundai.h
Introduced in #965. Most of the time, the correct one is chosen, but if the relay opens slowly, it can choose the wrong one.
> Hyundai: fix addr check race condition

- python/uds.py
Before the fix in https://github.com/commaai/panda/pull/1078, we'd time out on certain ecus that take longer than 100 ms to finish a full FW query response. Then, when a brand has multiple requests with no ecu whitelists and we'd receive frames from the previous request, throwing invalid consecutive frame errors.
Extending the timeouts on each received frame fixed most of those issues, however the 10 ms delay we have in the flow control message is a minimum, and it's quite possible that an ECU takes 100+ ms to send a frame and we'd time out on it.
This PR removes the frame interval we added to fix certain Hyundai ECUs and replaces it by sending the block size parameter. `IsoTpMessage` now needs to send a flow control message after each consecutive frame it gets from the ECU. This way, if …
> IsoTpMessage: param for single frame flow control

- board/safety/safety_ford.h
- tests/safety/test_ford.py
The DBC lists both the IPMA and PCM as receiving modules for the `CcAslButtnCnclPress` and `CcAsllButtnResPress` signals used to cancel/resume ACC.
Sending resume to both buses is confirmed to work by three testers, now it's just down to tweaking openpilot to get high reliability.
> Ford: allow sending buttons msg to camera

- board/safety/safety_hyundai_canfd.h
In HDA2 long mode, we use LFA to steer instead of LKAS.
> Hyundai CAN-FD: ignore LKAS steering on HDA2 long mode

- board/safety/safety_hyundai_canfd.h
- tests/safety/test_hyundai_canfd.py
`0x105` was found on the 2022 Hyundai Tucson Hybrid as the accelerator pedal signal and not any CAN-FD ICE models at the moment. The recent commits prevent the Tucson Hybrid to use this signal.
* https://github.com/commaai/panda/pull/999
**Prerequisite of**
* https://github.com/commaai/openpilot/pull/26086
> Hyundai: CAN-FD Hybrid gas pressed signal

- board/safety/safety_gm.h
- tests/safety/test_gm.py
> GM: match ECM standstill check

- board/drivers/can_common.h
- board/stm32h7/stm32h7x5_flash.ld
Move txgmlan buffer to bank D2 and tx2 to D1, give us 29120 bytes of free RAM.
F4 still has enough RAM.
(buffers for H7 a lot bigger because of the size of CAN FD msgs)
> H7: free up 29120 bytes of RAM

- board/safety/safety_gm.h
- board/safety/safety_honda.h
- tests/safety/test_gm.py
- tests/safety/test_honda.py
current_controls_allowed used to ensure:
- After enabling with gas pressed and disable on gas:
- we don't steer until gas is released (now allowed)
- we don't actuate long until gas is released (replaced with `longitudinal_allowed`)
- That we don't actuate anything with brake pressed and moving, which is an impossible situation (generic_rx_checks does this)
> Remove pre-enable state

- board/stm32h7/clock.h
- board/stm32h7/stm32h7x5_flash.ld
Need to explicitly enable clocks for SRAM1 and SRAM2 (in domain D2) so ram won't be lost in sleep state.
> bugfix: D2 SRAM clocks and CRun CPU state

- board/safety/safety_hyundai_common.h
- tests/safety/hyundai_common.py
With Hyundai, you can go from set to resume, or vice-versa, without first going to none/unpressed. openpilot treats this is as a falling edge of set of resume and enables, but panda doesn't since it requires going to none/unpressed.
> Hyundai: fix button enable controls mismatch

- board/safety/safety_gm.h
- tests/safety/test_gm.py
if we handle the buttons correctly and add multiple button presses per transition, openpilot will attempt to enable while controls_allowed stays low. This allows any transition to occur like openpilot (RES to SET for example)
for openpilot PR: https://github.com/commaai/openpilot/pull/26480/
> GM: handle run-away set speed

- board/bootstub.c
- board/drivers/uart.h
- board/early_init.h
- board/main.c
- board/pedal/main.c
- board/stm32fx/board.h
- board/stm32h7/board.h
Afaik this isn't in use anymore, and if the check fails the panda hangs without a decent way to debug.
> Remove external debug UART support

- board/safety.h
- board/safety/safety_honda.h
- board/safety/safety_toyota.h
- board/safety_declarations.h
on the road to removing `longitudinal_allowed` the safety modes
> safety: common interceptor checks

- board/drivers/can_common.h
Right now, it only resets if there's no CAN traffic at all anymore, but if the message disappears the state is kept.
Had this bug trigger in my car after an update, where CAN ignition went high because of an update-related message conflicted with the ignition signal on a different bus, but just disappeared after the update.
> Reset CAN ign when the specific message is not seen anymore

- board/drivers/uart.h
Buffer size was changed in https://github.com/commaai/panda/pull/1151. Since `rx_dma` is false I assume the buffer size should also be `FIFO_SIZE_INT`.
For some reason using a larger buffer causes the firmware to stop working on f4 devices when compiling on MacOS (`arm-none-eabi-gcc (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205`) or with the latest compiler from the arch repos ( `arm-none-eabi-gcc (Arch Repository) 12.2.0`). Since this is unexpected I assume you'd like to figure out why. 
`.bss` size is the same between both compilers, so it's not suddenly creating larger global variables.
> fix debug uart buffer size

- examples/query_fw_versions.py
Useful for aux (red) panda setups where we want to query on (in boardd's perspective) bus 5 for example
> query_fw_versions: add arg to not multiplex bus 1 to OBD-II port

- board/safety/safety_nissan.h
The error from the speed openpilot uses can be up to at least 0.6 m/s away using just one side of the car. Allows us to reduce the speed fudge for the angle rate limits: https://github.com/commaai/panda/pull/1254
> Nissan: use averaged left and right wheel speeds

- board/safety.h
- board/safety/safety_nissan.h
- board/safety/safety_tesla.h
- tests/safety/test_nissan.py
- tests/safety/test_tesla.py
Instead of adding an implicit fudge to the raw speed bp lists, add an explicit comment and offset in the angle limiting function. Will make it easy to keep the limits matching OP (some items in the v lists also weren't matching, which is unnecessary with a speed offset. fixed)
We can probably reduce the speed fudging even more, but I left a TODO comment to look at data to determine what a reasonable factor would be for now.
TLDR, what does this PR do?
- Change speed fudging from 2 m/s to 1 m/s (reduce tolerance)
- Fixes one point of the angle limit lookup tables not matching OP
- Makes the lookup tables match the tests' and OP's visually and by value
> Angle control: match openpilot limits

- tests/safety/common.py
- tests/safety/test_ford.py
- tests/safety/test_gm.py
Allows safety modes like Ford to use the _speed_msg as an actual speed message, for later curvature safety limits/tests
> safety tests: refactor for cars with standstill bits

- tests/safety_replay/helpers.py
- tests/safety_replay/replay_drive.py
Doesn't block first message any more
- `get_steer_value` returns torque or angle, which callee uses to set appropriate panda variable
- asserts that safety was initialized, even if it doesn't have a steering msg init method
> safety replay: make Ford work

- python/base.py
- python/spi.py
- python/usb.py
For consistency between SPI and USB.
* all communicats 
* SPI now supports an infinite timeout like USB
> python: non-zero default timeout

- board/safety/safety_volkswagen_pq.h
- tests/safety/test_volkswagen_pq.py
Corrected message name Anziege -> Anzeige. Null effect change.
In Panda, we only refer to the CAN arb ID with C/Panda constants (not opendbc/packer) so there are no dependencies.
> VW PQ: Corrected message name for ACC_GRA_Anzeige

- README.md
- tests/SConscript
- tests/libpanda/SConscript
Use homebrew gcc@12 from /opt/homebrew/bin to build panda tests, since apple clang does not support -std=gnu11 (https://opensource.apple.com/source/clang/clang-23/clang/tools/clang/docs/UsersManual.html#c)
I will include adding the required symlinks in mac_setup.sh script PR
```
cd /opt/homebrew/bin
ln -s gcc-12 gcc
ln -s g++-12 g++
```
> MacOS: use gcc-12 for building tests

- board/safety/safety_chrysler.h
- tests/safety/test_chrysler.py
We have tested for over a year that the Ram DT can handle 350 on the max steer. Any higher and the EPS will error out. Raising this here and then a PR can be made for the SelfDrive files.
> Raise max steer limits for Ram DT

- board/boards/black.h
- board/boards/board_declarations.h
- board/boards/dos.h
- board/boards/grey.h
- board/boards/pedal.h
- board/boards/red.h
- board/boards/red_v2.h
- board/boards/tres.h
- board/boards/uno.h
- board/boards/white.h
- board/drivers/fan.h
- board/stm32fx/llfan.h
- board/stm32h7/llfan.h
Wait a few seconds before turning the fan power off. If we turn it off with the rotor still spinning, the back EMF creates enough power to slightly power the fan controller and generate spurious tach edges.
> Tres: fan cooldown +  no stall recovery

- board/safety/safety_toyota.h
- python/__init__.py
- tests/safety/common.py
- tests/safety/test_toyota.py
When LTA param is set, enforces that we can never actuate torque with LKA. We also still test that LTA actuation is never allowed for any safety mode
> Toyota: base LTA safety

- tests/safety_replay/helpers.py
I think now it´s right!
```
BO_ 228 STEERING_CONTROL: 5 EON
SG_ STEER_TORQUE : 7|16@0- (1,0) [-4096|4096] "" EPS
```
> safety replay: update Honda steer value getter

- board/safety/safety_gm.h
- tests/safety/test_gm.py
- Reduce steer down limit to avoid hitting internal GM thresholds and associated windup
- Increase driver allowance to make the wheel firmer to driver torque (experimentally determined)
> GM: Reduce steer down limit and increase driver allowance

- python/uds.py
https://en.wikipedia.org/wiki/ISO_15765-2
> ISO-TP prepends one or more metadata bytes to the payload data in the eight byte CAN frame, reducing the payload to seven or fewer bytes per frame. The metadata is called the Protocol Control Information, or PCI. The PCI is one, two or three bytes. The initial field is four bits indicating the frame type, and implicitly describing the PCI length.
> IsoTpMessage: check CAN frame length

- python/uds.py
Fix a length bug from https://github.com/commaai/panda/pull/1311 when using subaddresses
Tests pass in https://github.com/commaai/panda/pull/1316
> IsoTpMessage: fix rx_len sanity checks

- python/uds.py
New bug found with https://github.com/commaai/panda/pull/1316. The number of bytes for a consecutive frame considered the subaddress, but not the number of bytes in a start frame (so we missed a byte)
None of Toyota's queries send more than 2 bytes at a time, so not a bug we'd normally hit (only an issue above 6 bytes).
> IsoTpMessage: don't skip a byte when sending consecutive frames to subaddress

- README.md
Fixes `fatal error: ffi.h: No such file or directory` when installing requirements on a fresh install of Ubuntu 20.04
> README: fix error while installing requirements

- README.md
Fixes `git` error when trying to build using the flash/recover scripts on a fresh install of Ubuntu 20.04
```
scons: Reading SConscript files ...
FileNotFoundError: [Errno 2] No such file or directory: 'git':
```
> README: fix git error while trying to build

- board/drivers/fdcan.h
- board/stm32h7/llfdcan.h
- tests/canfd/test_canfd.py
From datasheet:
`When an Rx FIFO is operated in overwrite mode and an Rx FIFO full condition is signaled,
reading of the Rx FIFO elements should start at least at get index + 1. The reason for that is
that it can happen that a received message is written to the message RAM (put index) while
the CPU is reading from the message RAM (get index). In this case inconsistent data may
be read from the respective Rx FIFO element. Adding an offset to the get index when
reading from the Rx FIFO avoids this problem. The offset depends on how fast the CPU
accesses the Rx FIFO.`
> Fix CAN message corruption on H7 under high load

- README.md
The order of the code snippets seem out of place.
You can't `pip install -r requirements.txt` until you clone the repo which is listed a few steps below.
Also separates the dependency code snippets for Ubuntu and macOS for better copy pasting.
> README: better instructions

- board/drivers/fdcan.h
- board/health.h
Previous implementation wasn't working as supposed.
Now it will show how many messages were lost due to get index offset and full FIFO.
> H7: Rx FIFO lost counter

- Dockerfile
- board/safety/safety_honda.h
- tests/safety/test_honda.py
For the new radarless HRV which actually uses the alt BRAKE_MODULE message for brake pressed (POWERTRAIN_DATA signal includes ACC braking)
> Honda Bosch Radarless: allow alt brake

- board/stm32h7/stm32h7_config.h
Draft, needs some more thought.  We're seeing some rare interrupt rate faults on all three buses.
I think we ideally want to set the interrupt rate based on the set speed.
> H7: fix CAN FD IRQ rate

- board/safety.h
- board/safety_declarations.h
@adeebshihadeh if there are three messages in the array (which is statically allocated length of 3 `const CanMsgCheck msg[3];`), then the addr of the fourth array item is not guaranteed to be 0 since it's out of bounds, right?
> safety: don't check out of bounds array item

- board/safety.h
Just a refactor PR to make behavior more apparent. It wasn't clear to me immediately how this worked, since the index is defaulted to 0. It only worked since the if statement above was identical. This makes it more explicit and easier to understand how it doesn't select incorrect indices.
For example, above, if this check never evaluates, msg_seen is never set and index is left at 0:
```c
if ((addr == addr_list[i].msg[j].addr) && (bus == addr_list[i].msg[j].bus) &&
(length == addr_list[i].msg[j].len)) {
addr_list[i].index = j;
addr_list[i].msg_seen = true;
break;
}
```
But below, it still checks if the message matches the index 0 `CanMsgCheck`, which looks like it may evaluate, but doesn't because the check is the same as above.
```c
if ((addr == addr_list[i].msg[idx].addr) && (bus == …
```
> safety: make addr index getter more explicit

- board/safety/safety_ford.h
- tests/safety/test_ford.py
the case this allows is similar to torque control limiting:
- new behavior: if EPS is faulted and controls are allowed (or some other condition to make OP not want to steer), safety should allow OP to send 0 curvature with `steer_control_type=False`
- previous behavior: it only checks `controls_allowed`, so angle error limits likely will block msgs
> ford: allow 0 curvature when controls is allowed if not steering

- board/safety.h
- tests/safety/common.py
Previously we were enforcing a disabled angle only when controls were not allowed. When `steer_control_enabled` bit is 0, you could set it to whatever you wanted. Not a huge deal unless an EPS has a bug where it actuates on that, or winds up torque on set of the bit again.
todo:
split from https://github.com/commaai/panda/pull/1369
> angle safety: enforce disabled angle when not steering

- board/safety/safety_ford.h
the lsb is either always 1 or 0 on most cars (varies by route on same car), and I've seen it go from 1 to 0 around the time the ignition fell after a long route, so something weird is going on. on some cars (Escapes), it's set but very inconsistent, bad cable or bad ECU?
think the counter signal def is correct as checksum also decrements by 2 (0xFF - counter), which would make the checksum invalid if we removed the bit
todo: understand from data if it consistently skips by 2, then check the three bit counter, while keeping four bits in the checksum calculation
> ford: disable counter check for second speed

- board/drivers/fan.h
- board/drivers/spi.h
- board/stm32h7/interrupt_handlers.h
- board/stm32h7/llspi.h
Reduces IRQ load from 28% -> 8% while running `panda.health()` in a loop.
> H7: remove busy wait on TXC

- board/safety/safety_tesla.h
Was broken in #1340. Haven't driven on it to test yet, but this is definitely more correct.
> DAS_control is on bus 2

- tests/safety_replay/test_safety_replay.py
Just added the gen2 flag which made it block all msgs since it wasn't reading the right bus to set controls allowed=True. However, strangely it's blocking msgs, did we change safety for global Subaru? I'll get a new route.
Prereq of https://github.com/commaai/panda/pull/1364
> Subaru: fix Impreza replay route

- board/safety.h
Related to https://github.com/commaai/panda/pull/1388
Originally at 0 degrees, we'd allow up in one direction and down in another: https://github.com/commaai/panda/blob/11ef24bc1642e5f6787dda2c1ff6a8a3c115c24a/board/safety/safety_toyota_ipas.h#L129-L130
Then in this Tesla safety refactor, it was switched to allow down in both directions: https://github.com/commaai/panda/pull/629
And Nissan copied Tesla's safety and tests.
> angle safety: add comment about rate limits at 0

- tests/safety/test_ford.py
Think it was used in two places but got rid of one usage before merging, not really needed. It's just the python floats that need to be rounded a bit `0.014000000000000002`
> Ford: remove unused function

- board/drivers/fdcan.h
- board/stm32h7/llfdcan.h
Main problem is that H7 with FDCAN FIFO for TX doesn't support transmission cancellation. So if we send messages on the bus that is not connected to anything - panda will lockup because of high call rate from Arbitration Error interrupt. 
On F4 we can cancel retransmission on error.
> H7: fix lockup on disconnected bus

- python/uds.py
Reverts https://github.com/commaai/panda/pull/1315
The iso-tp spec allows optimization of the data field only with certain frame types. So while we know of no cases where this is a problem, we should revert until we handle properly
```
10.4.2.2	 CAN frame data optimization (TX_DL = 8)
If this solution is used, the DLC does not always need to be 8. If the N_PDU to be transmitted is shorter
than 8 bytes, then the sender may optimize the CAN bus load by shortening the CAN frame data to
contain only the number of bytes occupied by the N_PDU (no padding of unused data bytes). CAN frame
data optimization can only be used for an SF, FC frame or the last CF of a segmented message.
```
> iso-tp: revert CAN frame length check

- board/main.c
We've seen one instance since initially shipping it. Lowering in preparation of enabling the IWDG peripheral.
> stricter simple watchdog

- board/safety.h
- board/safety/safety_honda.h
- tests/safety/test_gm.py
- tests/safety/test_honda.py
- GM wasn't affected because its inactive gas/regen was above min gas,
- Bosch Honda wasn't affected because it specifically sets min_gas to -30000 in the safety, when it should be 0,
- and Nidec Honda wasn't affected because inactive gas is 0.
ford may be affected as its inactive gas is below min gas
> safety: always allow inactive gas command

- board/safety/safety_ford.h
- tests/safety/test_ford.py
Split from https://github.com/commaai/panda/pull/1427
If this signal is 1, the camera will still send AEB commands on `ACCDATA_2` but the ABS doesn't actuate it.
More data/plots: https://github.com/commaai/openpilot/pull/28196#issuecomment-1552845171
> Ford safety: prevent disable AEB

- board/drivers/fdcan.h
Noticed this due to bus 2 timeouts in our Optima. Bus 2 drops out for several boardd cycles, followed by a cycle with all the missing messages from the previous cycles. The Optima seems to be a worst case for this, since bus 2 only has a single 100Hz message, where as the EV6 has tons of messages from the camera. 
```
ae78716c0595008d|2023-06-06--10-25-07--5
```
The RX IRQ is fired with no flags set in the IR register, including `FDCAN_IR_RF0N`, the "new message" flag, despite the RX FIFO status register saying messages are available. Eventually, an IRQ comes in with `FDCAN_IR_RF0N` set and the messages are read.
> H7: fix CAN RX delay

- board/safety/safety_ford.h
- tests/safety/test_ford.py
The roll signal isn't used in openpilot, and isn't populated on the Ford Focus Mk4 (it is always [`6.6086` No data exists](https://github.com/commaai/opendbc/blob/master/ford_lincoln_base_pt.dbc#L12423)). We still have the yaw signal.
Route: `e886087f430e7fe7|2023-06-14--13-19-55`
> Ford: don't check vehicle roll quality flag

- python/uds.py
`TypeError: unsupported format string passed to NoneType.__format__`
either way, this would fail. None can't be formatted like this and hex(int) is a string, not int (required int by the `:x` specifer)
> uds: fix TypeError for invalid subfunctions

- board/drivers/bxcan.h
- board/drivers/fdcan.h
- board/main_comms.h
FDCAN_IR register gets erased after writing even just one flag. Because of that we were not recording all errors fired.
> H7: fix FDCAN_IR register check

- examples/query_fw_versions.py
now you can:
- preserve previous behavior, don't use `--subaddr` or `--sub_addr`
- query a sub-address for an address with `--addr 0x750 --subaddr 0xf`
- query a sub-address for all addresses with `--subaddr 0xf`
- scan 0x00-0xff for an address with `--addr 0x750 --subaddr scan`
- scan 0x00-0xff for all addresses with `--subaddr scan`
> query_fw_versions: sub-address support

- examples/query_fw_versions.py
- python/uds.py
We weren't checking if the sub-address acknowledgement in the response was correct. This adds a sanity check, and catches in query_fw_versions.py for when you're querying the whole address space for sub-addresses (to find addresses which have them).
Before this you'd get something like:
```python
comma@tici:/data/openpilot/panda/examples$ ./query_fw_versions.py --bus 0 --addr 0x710 --subaddr 0x1                                                                                                               
querying addresses ...                                                                                                                                                                                             
0x710, 0x1:   0%| …
```
> CanClient: check invalid sub-addresses

- board/drivers/bxcan.h
- board/drivers/fdcan.h
- board/health.h
- python/__init__.py
Would be helpful to have interrupt counter in the CAN health packet
Also data should be updated on request (except when error interrupt was fired). With previous method if CAN core stopped to fire interrupts - health packet won't be updated.
> CAN health: add IRQ call and core reset counters

- board/main.c
We won't be able to rely on this for all devices, so remove where not strictly necessary.
> update old comment

- board/crc.h
- board/drivers/spi.h
- python/spi.py
- python/utils.py
- tests/hitl/8_spi.py
Now the SPI protocol version request contains everything in the USB descriptors and everything that's relevant for enumerating/listing a panda and reflashing a panda.
> SPI: send bootstub status in version request

- board/boards/board_declarations.h
- board/boards/dos.h
- board/boards/red_v2.h
- board/boards/tres.h
- board/boards/uno.h
- board/boards/unused_funcs.h
- board/main.c
- tests/print_logs.py
- tests/setup_device_ci.sh
Logs the time from panda bootkick to the ABL triggering the SOM GPIO. Looks like this:
```
65     2023-07-12 22:09:30      0 - main start
66     2023-07-12 22:10:17     47 - bootkick
67     2023-07-12 22:10:20     50 - device booted
```
> log device boot time

- __init__.py
- python/__init__.py
- python/constants.py
- python/spi.py
if one process is sending CAN messages with a full TX buffer, this allows other processes to still access the device in between retries
> python: lock hw device inside loop

- board/safety/safety_honda.h
Made common with safety.h's `generic_rx_checks` here (deletion in honda was simply forgotten about): https://github.com/commaai/panda/commit/5b1494514042721b63f71254700ddcf94dbbd9c7
You can see we only use this boolean when the same check is true:
https://github.com/commaai/panda/blob/1154eb2d75f6a0b416d587b22177c759acf5f8e4/board/safety.h#L254-L277
> Honda: remove duplicated relay transition time check

- board/safety/safety_subaru.h
- tests/safety/test_subaru.py
ES_LKAS_ANGLE uses centigrees as its measurement, so convert the measured steering angle to centigrees
> Subaru: convert measured angle to centigrees

- tests/hitl/4_can_loopback.py
That's the fix I found for CI issue with total_error_cnt, not yet sure why it is not being reset with fixtures reinit. Still think this is real bus disturbance.
> set OBD to False after test

- tests/safety/test_gm.py
Moved longitudinal-only tests to the longitudinal class. What other safety modes do. GM Camera skips these already
> GM: clean up longitudinal safety test

- board/safety/safety_subaru.h
- tests/safety/test_subaru.py
Current cancel request method (using simulated buttons) uses the same message that contains Cruise_Throttle meaning we could have sent any throttle we wanted
> Subaru: cancel safety

- board/safety.h
- board/safety_declarations.h
rename alt to transmission rpm, to make it more clear
> Safety: Rename alt transmission rpm

- board/safety/safety_hyundai_canfd.h
- board/safety/safety_hyundai_common.h
The parsing of the CANFD `ACC_STATUS->ACCMode` signal only considers the first two bits (0x3 instead of 0x7), so it would consider any value from 1 to 3 to be enaged, and 0 and 4 to be disengaged. Which is mostly correct, since the EV6 route I found has it at 4 when disabled.
When the car enters a fault status (3), only then is there a mismatch between openpilot and panda. Will fix this by:
- correctly parsing the whole 3 bit signal,
- checking the same specific values openpilot does, 
- and adding a test to test_models to check cruise state, not only controlsAllowed, which shows a mismatch in most HKG routes (doesn't need the fault status to come up) - https://github.com/commaai/openpilot/pull/29423
> Hyundai CAN FD: fix PCM cruise check

- board/safety/safety_body.h
this has no effect on safety, this only matches what openpilot sets.
> body: set vehicle_moving

- board/main.c
- board/safety.h
- board/safety/safety_ford.h
- board/safety/safety_gm.h
- board/safety/safety_honda.h
- board/safety/safety_hyundai_common.h
- board/safety/safety_volkswagen_pq.h
Unified the assignment of `controls_allowed` with boolean values. This change improves consistency by using boolean values throughout.
> Safety: unify `controls_allowed` with boolean

- board/stm32h7/peripherals.h
We call detect_board() before current_board->init() so no need for that code (and already being initialized as analog, so should save some power too)
@robbederks agree?
> H7: clean up peripherals.h

- board/safety/safety_honda.h
- tests/safety/test_honda.py
Only relevant with https://github.com/commaai/openpilot/pull/26463. Enables on falling edge of button to any other button, except cancel.
See PR for Hyundai: https://github.com/commaai/panda/pull/1152
> Honda: match openpilot button enable check

- python/uds.py
reverts some of https://github.com/commaai/panda/pull/1314
returns if updated, rather than if consecutive frame
for https://github.com/commaai/openpilot/pull/29654
> iso-tp: return if updated

- python/uds.py
Reverts https://github.com/commaai/panda/pull/1487 and https://github.com/commaai/panda/pull/1610.
IsoTpParallelQuery code in openpilot didn't handle response pending after these changes, which requires the IsoTpMessage object to handle multiple first/single frames. This affected a few VWs on master.
Think it's better to revert and verify again than to patch.
> Revert "iso-tp: more checks (#1487)"

- board/safety/safety_toyota.h
- tests/safety/test_toyota.py
Reverts commaai/panda#1612
need to bump panda for a different revert and there's a diff in test_models (valid, but need to think how to cleanly ignore it)
> Revert "Toyota: ACC message relay check (#1612)"

- board/drivers/can_common.h
- board/drivers/spi.h
Reasoning for SPI:
DMA is in D2 domain, so SRAM1 and SRAM2 are the fastest.
Reasoning for FDCAN:
ITCM RAM and DTCM RAM are the fastest for cortex core access, no need to use cross domain links.
Also AXI SRAM will be needed for SDMMC driver buffer soon. (next PR)
=======SUMMARY FOR H7 FILE ../board/obj/panda_h7.elf=======
SECTION: .flash size: 1048576 USED: 64308(6.13%) FREE: 984268
SECTION: .dtcmram size: 131072 USED: 100400(76.60%) FREE: 30672
SECTION: .itcmram size: 65536 USED: 59904(91.41%) FREE: 5632
SECTION: .axisram size: 327680 USED: 294912(90.00%) FREE: 32768
SECTION: .sram12 size: 32768 USED: 4096(12.50%) FREE: 28672
SECTION: .sram4 size: 16384 USED: 0(0.00%) FREE: 16384
SECTION: .backup_sram size: 4096 USED: 0(0.00%) FREE: 4096
> H7: reorganize RAM

- board/jungle/main.c
- board/main.c
Will help support to better understand if panda froze before USB/SPI init
> enable red and green leds until USB/SPI init

- board/safety/safety_volkswagen_pq.h
- tests/safety/test_volkswagen_pq.py
as far as I can tell, VW doesn't need any special logic around the steer req frames. It only sets HCA_ENABLED to false when apply_steer is zero, which is fine in the current panda logic:
https://github.com/commaai/openpilot/blob/master/selfdrive/car/volkswagen/carcontroller.py#L56
https://github.com/commaai/panda/blob/master/board/safety.h#L573
> VW PQ: Check steer req bit

- board/drivers/can_common.h
Previous signal was checking whether the immobilizer ID was being published. New signal is the power mode. The previous signal used before the immobilizer signal was the "backup" power mode which is noisy and doesn't describe cranking or accessory (https://github.com/commaai/panda/pull/845).
This new [`SystemPowerMode`](https://github.com/commaai/opendbc/pull/953) describes the four ignition states: off, accessory, (on, and ignition together), and cranking.
The problem with the current signal is that the immobilizer signal remains high in accessory mode, where various ECUs can fault or shut off ([the EBCM on the Chevy Bolt](https://github.com/commaai/panda/assets/25857203/29182ec7-0984-47ad-b0b4-deedbb29d0de), [the PSCM on the ASCM …
> GM: change ignition signal

- board/safety/safety_nissan.h
- tests/safety/test_nissan.py
Now matches the DBC. No reason not to consider the true sign of the angle in panda safety. Removes weird negative scaling that breaks proper sample parsing tests (since getting min and max will not be correct after dividing by `DEG_TO_CAN`)
For https://github.com/commaai/panda/pull/1679
> Nissan: consider true sign in safety

- board/safety/safety_hyundai.h
- tests/safety/common.py
- tests/safety/test_subaru.py
Split from LTA PR https://github.com/commaai/panda/pull/1189, added in: https://github.com/commaai/panda/pull/1528
This measurement safety test that's specifically for angle should not have been split out into a generic test that can't be modified from the angle test. For example, we need to parameterize the max angle for Ford and Toyota LTA.
Subaru should just have used the angle test class
> safety tests: clean up measurement tests

- board/safety/safety_hyundai.h
- tests/safety/common.py
Noticed in https://github.com/commaai/panda/pull/1695
This asserts that above the driver torque allowance, torque command messages are blocked. However here, they were blocked due to the sign of the torque command flipping when `sign` is `1` (when `sign` is `-1`, everything was tested properly), since `self.assertFalse(self._tx(self._torque_cmd_msg(-self.MAX_TORQUE)))` doesn't multiply by `sign`
Now we test 2x the range
> safety tests: fix driver torque override test

- board/safety/safety_gm.h
- board/safety/safety_hyundai.h
- tests/safety/common.py
- tests/safety/test_gm.py
- tests/safety/test_hyundai.py
Changed in https://github.com/commaai/panda/pull/503 without changing any of the tests or OP. Panda safety was allowing 1.26x more driver torque than desired before it asserted winddown.
A bug like this is caught with meas/EPS torque safety because of the measurement test we have, we just didn't have one for driver torque safety.
---
Now we RX real driver torque messages and run the existing override tests on that, which is a more complete end to end test to catch this (similar to angle test with current angle and vehicle speed)
> Hyundai CAN: fix driver torque safety scaling

- tests/safety/common.py
Fix regression from https://github.com/commaai/panda/pull/1579
Attr is always the last attr we loop through, which happens to be `unittest` due to adding generators and not evaluating the values.
Example:
```python
AssertionError: 1 is not false : transmit of addr=0x2e6 bus=0 from unittest during TestToyotaStockLongitudinalTorque was allowed
```
Fixed:
```python
AssertionError: 1 is not false : transmit of addr=0x2e6 bus=0 from TestToyotaAltBrakeSafety during TestToyotaStockLongitudinalTorque was allowed
```
> safety test: fix incorrect error message

- board/safety/safety_honda.h
- board/safety/safety_tesla.h
- board/safety/safety_toyota.h
- tests/libpanda/safety_helpers.h
`gas_interceptor_detected` is already cleaned up by the main safety hook init function
Honda had its own safety test init function which was refactored out, leaving just this behind: https://github.com/commaai/panda/commit/d68356b9246f37a73c91a1b1216c3f4f4ac49896#diff-a8952cdeddfbad7fb89cc950ad6bc4fba0a01dd1609e78d75a576a8c9a1da12c
Tesla added here: https://github.com/commaai/panda/pull/1340
> safety tests: clean up state reset

- board/safety/safety_ford.h
- tests/safety/common.py
- tests/safety/test_chrysler.py
- tests/safety/test_ford.py
- tests/safety/test_gm.py
- tests/safety/test_honda.py
- tests/safety/test_hyundai.py
- tests/safety/test_hyundai_canfd.py
- tests/safety/test_mazda.py
- tests/safety/test_nissan.py
- tests/safety/test_subaru.py
- tests/safety/test_subaru_preglobal.py
- tests/safety/test_tesla.py
- tests/safety/test_toyota.py
- tests/safety/test_volkswagen_mqb.py
- tests/safety/test_volkswagen_pq.py
Expands coverage for https://github.com/commaai/panda/pull/1699, also allows for safety tests to specify multiple relay malfunction addresses for full coverage. This prepares us for Toyota radar disable safety in the new RAV4s as well!
---
The new relay malfunction test keeps the same coverage while also asserting that the addresses that cause a relay malfunction match what is in the safety test; this catches some cases where safety was setting a relay malfunction and we weren't ensuring that: Hyundai CAN FD long, Ford Long, GM long, etc.
---
> safety tests: support multiple relay malfunction addresses

- board/boards/board_declarations.h
- board/boards/tres.h
- board/drivers/bootkick.h
- board/health.h
- board/main_comms.h
- python/__init__.py
- tests/som/test_bootkick.py
> SOM boot recovery

- tests/safety/test_elm327.py
Split from https://github.com/commaai/panda/pull/1699, adds complete ELM coverage. LIN tx test using reference: https://github.com/commaai/panda/commit/ad79b7f4d26bcb0245a8b85566df2aefe99083bd
> safety: add ELM327 safety test

- board/safety/safety_hyundai.h
- tests/safety/test_hyundai.py
Caught by https://github.com/commaai/openpilot/pull/30443. Has no effect on real routes since this signal is never 3
> Hyundai: fix brake pressed bitmask

- board/safety/safety_ford.h
- tests/safety/test_ford.py
Split from https://github.com/commaai/panda/pull/1718, caught in https://github.com/commaai/openpilot/pull/30443. Similar bug to: https://github.com/commaai/panda/pull/1724
openpilot checks that this value == 1 to be in standstill, but panda was checking it to be 0, when it's a 2 bit signal (can be 2=NoDataExists, 3=Faulty).
> Ford: fix possible standstill mismatch

- tests/safety/common.py
- tests/safety/test_honda.py
- tests/safety/test_toyota.py
Split from https://github.com/commaai/panda/pull/1735
All safety modes that inherit from the interceptor test so far use the same DBC msg structure, only thing that is different is scaling. This matches openpilot's message creation which is also generic.
> safety tests: common interceptor msg

- tests/safety_replay/helpers.py
Wrote this to make sure that https://github.com/commaai/panda/pull/1752 wasn't only an issue for Toyota, might as well merge. Initializes safety properly with PR mentioned.
This supports running on segments already enabled.
> safety replay: support Nissan

- board/safety/safety_ford.h
- board/safety/safety_nissan.h
- board/safety/safety_subaru.h
- board/safety/safety_tesla.h
- board/safety_declarations.h
sample_t supports int, so we needed a way to store float, hence rounding and vehicle speed factor. Put this duplicate math in a macro
> safety: macro to update vehicle speed

- examples/can_bit_transition.py
- examples/can_logger.py
1. Add time field to `can_logger.py`, where the time use `time.time()` when received the CAN message.
2. Update `can_bit_transition` to support `can_logger` format.
> examples: Make can_bit_transition.py support can_logger.py

- board/safety/safety_ford.h
- tests/safety/test_ford.py
Unknown what effect this signal has if set while other signal is inactive, so it's best to assert safety on this. We do this for other safety modes too: https://github.com/commaai/panda/blob/bb75afc84e4d33af1554ada81851547db648e33e/board/safety/safety_hyundai.h#L242-L243 and https://github.com/commaai/panda/blob/bb75afc84e4d33af1554ada81851547db648e33e/board/safety/safety_hyundai_canfd.h#L272-L273
It just happened that a byte value of 0 is the actual inactive value (-5 m/s^2), and that it actuates gas.
> Ford: check predicted gas

- board/safety/safety_honda.h
I recall fixing this on a branch, but not sure where it got lost. This fixes a mismatch in https://github.com/commaai/openpilot/pull/30443 when running on randomly-ordered tests since the previous value is sticking around
> Honda: reset prev brake switch

- SConscript
For [#30161](https://github.com/commaai/openpilot/issues/30161)
> CI: Translate abspath to relpath for build. 

- examples/can_bit_transition.py
Sort signals numerically instead of lexicographically.
Example output before:
```
id 0:140 0 -> 1 at byte 0 bitmask 64
id 0:1e9 0 -> 1 at byte 0 bitmask 64
id 0:1fc 0 -> 1 at byte 4 bitmask 3
id 0:214 0 -> 1 at byte 1 bitmask 80
id 0:2f9 0 -> 1 at byte 5 bitmask 40
id 0:be 0 -> 1 at byte 1 bitmask 84
id 0:be 1 -> 0 at byte 1 bitmask 2
id 0:be 1 -> 0 at byte 5 bitmask 80
id 0:c9 0 -> 1 at byte 5 bitmask 1
id 0:d1 0 -> 1 at byte 0 bitmask 3
id 0:d1 0 -> 1 at byte 4 bitmask 66
id 0:f1 0 -> 1 at byte 0 bitmask 66
id 0:f1 0 -> 1 at byte 1 bitmask 88
id 0:f1 1 -> 0 at byte 4 bitmask 176
id 2:170 0 -> 1 at byte 2 bitmask 88
id 2:1e9 0 -> 1 at byte 0 bitmask 16
id 2:212 0 -> 1 at byte 0 bitmask 32
id 2:212 0 -> 1 at byte 1 bitmask 80
id 2:212 0 -> 1 at byte 4 bitmask 88
id 2:214 0 -> 1 at byte 0 …
```
> Sort output of can_bit_transition script numerically

- board/safety/safety_volkswagen_mqb.h
- tests/safety/test_volkswagen_mqb.py
Part of the work for commaai/openpilot#23274. Filter LH_EPS_03 in the bus 0->2 direction, and allow openpilot to transmit its own version.
> VW MQB: Safety update for EA timeout fix

- tests/misra/coverage_table
- tests/misra/install.sh
- tests/misra/suppressions.txt
- tests/misra/test_misra.sh
According to the release notes, `Misra C 2012 compliance has been "completed"`.
> update cppcheck to 2.13

- tests/misra/test_misra.sh
Before it was not caching into `--cppcheck-build-dir` because each folder can only used for one file and we have 3 files to check. After caching if there is no change in compilation then it would take ~1s, and only recache specifically changed files. I disabled the sanity check to only check if the folder doesn't already exists because checkers are not called if the files are cached.
```
** PANDA F4 CODE **
Checking board/main.c ...
nofile:0:0: information: Active checkers: 177/792 (use --checkers-report=<filename> to see details) [checkersReport]
** PANDA H7 CODE **
Checking board/main.c ...
nofile:0:0: information: Active checkers: 177/792 (use --checkers-report=<filename> to see details) [checkersReport]
** PEDAL CODE **
Checking board/pedal/main.c ...
nofile:0:0: information: Active …
```
> Enable caching in test_misra

- board/drivers/spi.h
- tests/misra/suppressions.txt
for #1794 
lmk if I missed anything
> enable misra-c2012-5.8

- tests/misra/test_misra.sh
- tests/misra/test_mutation.py
Now mutation test can cache from ~45s to ~10s, replace `tempDirectory()` so that we can name the directory ourselves
```
9.21s call     panda/tests/misra/test_mutation.py::test_misra_mutation[None-None-False]
8.92s call     panda/tests/misra/test_mutation.py::test_misra_mutation[board/stm32h7/llfdcan.h-s/return ret;/if (true) { return ret; } else { return false; }/g-True]
8.63s call     panda/tests/misra/test_mutation.py::test_misra_mutation[board/safety/safety_toyota.h-s/is_lkas_msg =.*;/is_lkas_msg = addr == 1 || addr == 2;/g-True]
8.48s call     panda/tests/misra/test_mutation.py::test_misra_mutation[board/stm32fx/llbxcan.h-s/1U/1/g-True]
(6 durations < 0.005s hidden.  Use -vv to show these durations.)
=================================================================== 4 passed in …
```
> Enable cache for MISRA mutation test

- board/stm32h7/lli2c.h
- tests/misra/suppressions.txt
> enable misra-c2012-2.7 

- SConscript
- SConstruct
This brings the compilation_db command to panda as well. We currently have it on opnepilot and it helps setup IDEs nicely.
_This was first introduced in openpilot on https://github.com/commaai/openpilot/pull/19533 by @adeebshihadeh_
This MR basically brings that to panda and it has two ways it can work. 
1. When building as standalone the panda project, you can provide `--compile-db` same as in openpilot.
a. This will create a `compile_commands.json` on the `panda` folder with only panda stuff. 
3. As part of building the openpilot project and panda is a submodule. By adding the tools to the env on the `panda/SConscript` we basically signal `SConstruct` to generate the compilation db for our stuff as well. 
a. This will add to the `compile_commands.json` that openpilot generates on the …
> Adding compilation_db to panda builds

- board/safety.h
- board/safety_declarations.h
- tests/misra/suppressions.txt
This is a bit of a workaround for what seems like a bug with cppcheck dumps dropping rx_msg_safety_check def arguments  after the first const function pointer type.
> enable misra-c2012-8.2

- python/__init__.py
When a script changes the baudrate of the panda this becomes a persistent change until the panda is power cycled. This can cause other scripts to not work. This wasted me quite a bit of time debugging.
Moved the call to `can_reset_communications` to the connect function to make behavior consistent between creating a new panda object and calling `reset()`.
Feel free to close if you think this is intended behavior. This can also be solved by improving user feedback (e.g. printing a warning on connect).
> Reset baudrate when connecting from Python

- tests/safety/test.sh
distribute per test not per file
no faster in CI, but about 4 seconds faster per hw type locally with 16 procs (-n auto)
> safety: test with default pytest dist (load)

- board/safety/safety_elm327.h
- tests/misra/coverage_table
- tests/safety/test_elm327.py
Behind the OBD gateway, at the camera, 0x24b -> 0x64b is the only ECU that responds to tester present (camera). You can also see this range in GM's version of ISO-TP/UDS docs.
> ELM safety: allow GM diagnostic camera address (0x24B)

- board/boards/black.h
- board/boards/dos.h
- board/boards/red.h
- board/boards/red_chiplet.h
- board/boards/uno.h
In the rest of the codebase `CAN1`, `CAN2 `, `CAN3 `refer to stm32 peripheral only.
Don't use harness CAN bus labeling to avoid confusion with panda peripheral.
> Fix CAN comment

- board/drivers/harness.h
USB-C internally routes sbu1 to sbu2 in the default orientation.  This single comment should reduce the confusion about meaning of flipped/normal OBD-C . 
Background:
I was designing OBD2 adapter for OBD-C and needed to understand exactly relationship between OpenPilot buses, STM32 peripherals, and harness buses.
Unfortunately there was [conflicting](https://github.com/lukasloetkolben/OpenpilotHardware/pull/1) information from the community. Ultimately, [finding out](https://github.com/commaai/panda/pull/435#issuecomment-1928036952) how USB-C cables are built was the key to understanding. Also I can confirm accuracy of the comma [documentation](https://github.com/commaai/neo/blob/master/car_harness/OBD-C.sch.pdf).
> USB-C cable orientation clarification

- tests/safety/test_coverage.sh
Invokes the native browser for baremetal/virtual Ubuntu, and the Windows browser for WSL users.
> invoke system browser for coverage reports

- pyproject.toml
In pytest 8.0.0, it collects all files, even if you only specify one file to run. Then pytest-cpp will execute these two files since they are executable (an issue if you have openpilot's environment)
[Relevant issue](https://github.com/pytest-dev/pytest/issues/11974)
> fix pytest loop

- board/can_comms.h
- tests/misra/.gitignore
- tests/misra/test_misra.sh
- tests/misra/test_mutation.py
For #1847
Update on the [issue](https://trac.cppcheck.net/ticket/12440):
After some communication with the cppchecker team, it seems that specific misra violations return 0 with the both cases: 
- running the misra addon directly over the dump 
- running it with the `--addon` flag. 
Hence to exit when we find any misra violation, I have decided to grep the output log for `misra violation`
> Make MISRA results consistent across cppcheck runs

- board/boards/dos.h
- board/boards/unused_funcs.h
- board/bootstub.c
- board/drivers/gmlan_alt.h
- board/drivers/interrupts.h
- board/drivers/uart.h
- board/flasher.h
- board/provision.h
- board/stm32fx/lluart.h
- tests/libpanda/safety_helpers.h
- tests/misra/suppressions.txt
- tests/misra/test_misra.sh
Flagged by cppcheck. Need to figure out a way to enable this in CI and have cppcheck do this check globally instead of on each individual build (F4/H7 app, boostub, jungle, etc.).
> (almost) enable cppcheck unusedFunction

- board/safety/safety_chrysler.h
- board/safety/safety_ford.h
- board/safety/safety_gm.h
- board/safety/safety_honda.h
- board/safety/safety_hyundai.h
- board/safety/safety_hyundai_canfd.h
- board/safety/safety_subaru.h
- board/safety/safety_subaru_preglobal.h
- board/safety/safety_toyota.h
- board/safety/safety_volkswagen_mqb.h
- board/safety/safety_volkswagen_pq.h
- board/safety_declarations.h
Refactor GET_BIT to return a `bool`, which makes it easier to use while maintaining MISRA compliance.
Cast directly from an int to a bool doesn't work, but old-school double-negation does the job and seems to be permitted. It did leave a [single breakage in the Chrysler port](https://github.com/commaai/panda/pull/1877/commits/a2e87257a8a220fd0bca707957c34e1759b479d3). While MISRA 10.4 does make specific mention of matching essential types on both sides of a ternary op, it's not clear why it didn't think both sides were the same here. An additional cast to bool worked, so there may be a subtlety between Boolean and _essentially_ Boolean types, or perhaps a bug in the type checker.
> refactor GET_BIT to be MISRA friendly

- board/safety/safety_volkswagen_pq.h
- tests/safety/test_volkswagen_pq.py
This is #1670 but now with a test. Won't be used immediately in stock openpilot, but will allow forks to explore tuning the other control variant. It's not yet been made to behave super well, but there's interesting potential.
PQ only. It's technically documented for MQB as well, but on the vehicles we tested, the EPS acts like it has no maps for it.
> VW PQ: Allow either HCA mode

- board/safety/safety_ford.h
- tests/safety/test_ford.py
We can't check the counter because on some platforms, it skips seemingly randomly. Both on the side the gateway that openpilot is on, and behind the gateway directly on HSCAN2 - bd37e43731e5964b|2023-06-02--20-53-11
Confirmed that the checksum mismatches are also present on the other side of the gateway https://discord.com/channels/469524606043160576/1114344869314429039/1210771260225622109
> Ford: ignore 2nd speed checksum

- board/drivers/fdcan.h
For CAN-FD hardware, fix forwarded-to bus logging over USB/SPI to match [earlier hardware](https://github.com/commaai/panda/blob/70578a11f06a280e5f877d70e8998ba4ff001377/board/drivers/bxcan.h#L91). Actual forwarding happens correctly, but on USB/SPI it's currently logged with the received bus and should be the target bus.
**Broken:** `f39cf149898833ff/2024-02-15--17-27-50/0`
**Fixed:** `f39cf149898833ff/2024-02-22--01-17-23/0`
> fix forwarded bus logging for CAN-FD hardware

- board/stm32h7/clock.h
First byte of `PWR->CR3` is locked after the first write, so we can't init all H7 with the LDO, then switch to SMPS if available. We'll have to figure out another way to detect package or panda type before this init.
> 723 power init

- board/drivers/usb.h
just removes the old popup for cabana; webusb support is still intact
> Remove WebUSB popup

- python/uds.py
Try 2 of https://github.com/commaai/panda/pull/1487 and https://github.com/commaai/panda/pull/1610. Potentially fixes https://github.com/commaai/openpilot/issues/32242
In short, this adds checks to first and single ISO-TP frame types. If you receive a first frame, the next message must be consecutive, or the new assertions in first and single are raised. You can receive as many single frames as you want without issue.
An additional rx length check is added to ensure that `rx_dat` isn't unset in the first frame hook (it previously accepted `m._isotp_rx_next(b'\x10\x08')`) which isn't a [valid CAN frame size](https://en.wikipedia.org/wiki/ISO_15765-2).
---
This would cause the EPS to now *successfully* respond for:
- `297b4b460f361603/2023-06-14--16-55-16`
- …
> IsoTpMessage: extend timeout on first frame response

- .github/workflows/test.yaml
- pyproject.toml
- tests/misra/install.sh
- tests/misra/test_mutation.py
this has been failing but pytest.main doesn't exit, you need to exit manually...
```
_____________________ test_misra_mutation[None-None-False] _____________________
[gw0] linux -- Python 3.11.4 /root/.pyenv/versions/3.11.4/bin/python3
fn = None, patch = None, should_fail = False
@pytest.mark.parametrize("fn, patch, should_fail", mutations)
def test_misra_mutation(fn, patch, should_fail):
with tempfile.TemporaryDirectory() as tmp:
shutil.copytree(ROOT, tmp, dirs_exist_ok=True)
if fn is not None:
r = os.system(f"cd {tmp} && sed -i '{patch}' {fn}")
assert r == 0
r = subprocess.run("tests/misra/test_misra.sh", cwd=tmp, shell=True)
failed = r.returncode != 0
>       assert failed == should_fail
E       assert True == False
test_mutation.py:81: AssertionError
```
> CI: fix misra mutation tests

- README.md
I think `panda.set_safety_mode(Panda.SAFETY_ALLOUTPUT)` is always required when using panda without openpilot.
Also  "message" string in data was causing error.
> Readme: can send commands

- board/safety_declarations.h
- board/utils.h
- tests/misra/suppressions.txt
- tests/misra/test_misra.sh
Allow gcc's (and compatible compilers) `__typeof__` extension for type safety and concise code.
Btw, [C23](https://en.cppreference.com/w/c/language/typeof) has `typeof` natively, but cppcheck doesn't support yet - according to the [manual](https://cppcheck.sourceforge.io/manual.pdf).
Links https://github.com/commaai/panda/issues/1954 https://github.com/commaai/panda/issues/1794 https://github.com/commaai/panda/pull/1926
> Enable misra-c2012-1.2

- tests/misra/test_misra.sh
- tests/misra/test_mutation.py
Mutations test fails due to git diff running in a temp folder.  Only when running **locally** for some reason.  Error:
```
MISRA coverage table doesn't match. Update and commit:
Before: /home/dzid_/openpilot/panda/tests/misra
--------------------------------- Captured stderr call ----------------------------------
HEAD is now at 7cb8f2bc6 Fix #12726: Update for CheckOrderEvaluation (#6448)
fatal: not a git repository: /tmp/tmpowwsj6_q/../.git/modules/panda
```
This PR patches this problem.  
------
I am bit confused though:
- I verified `$DIR`, `$CPPCHECK_DIR`, `$PANDA_DIR`  point to temp folder.
- However htop shows cppcheck process running in the root, not temp
- _and_  cppcheck dump files are created in the root (and [not deleted](https://github.com/danmar/cppcheck/pull/4757)): 
``` …
```
> misra mutations test - git diff error fix

- tests/misra/test_misra.sh
I introduce a bug last time. 
This PR: 
- fixes `git diff $CHECKLIST` command
- avoids exitcode=2 (already configured for cppcheck)
> Cppcheck checklist bugfix

- board/main.c
Potential fix for https://github.com/commaai/openpilot/issues/32070.
I was able to very easily reproduce:
- send a query to the OBD port while comma power is unplugged
- get a returned CAN message from the can core (?!) which we log as if it actually sent
- wait 5s, then switch away from the OBD port/to the powertrain bus 1
- message still in the can core gets sent with no returned can packet
this then puts the ECU into either one of two states, both are bad:
1. it's waiting for our flow control continue while we're sending another single frame, so it doesn't respond
2. the gateway sends the flow control continue for us and we end up skipping the first few consecutive frames
---
If I understand this correctly, we already had a fix for this, but might have not have always triggered: …
> clear stuck CAN messages before switching multiplexing

- Dockerfile
- board/jungle/scripts/can_printer.py
- board/jungle/scripts/echo_loopback_test.py
- board/jungle/scripts/loopback_test.py
- examples/can_logger.py
- examples/tesla_tester.py
- python/__init__.py
- python/ccp.py
- python/isotp.py
- python/xcp.py
- tests/black_white_loopback_test.py
- tests/black_white_relay_endurance.py
- tests/black_white_relay_test.py
- tests/bulk_write_test.py
- tests/can_printer.py
- tests/canfd/test_canfd.py
- tests/echo.py
- tests/elm_car_simulator.py
- tests/hitl/3_usb_to_can.py
- tests/hitl/4_can_loopback.py
- tests/hitl/6_safety.py
- tests/hitl/9_harness.py
- tests/hitl/helpers.py
- tests/loopback_test.py
- tests/message_drop_test.py
- tests/safety/common.py
- tests/safety/test_ford.py
- tests/safety/test_hyundai.py
- tests/usbprotocol/test_comms.py
- tests/usbprotocol/test_pandalib.py
openpilot PR: https://github.com/commaai/openpilot/pull/33146
> deprecate busTime

- board/SConscript
- board/stm32h7/board.h
- board/stm32h7/clock.h
(another attempt at #1975)
Unfortunately, I couldn't find a good way to determine if the chip has the SMPS (725) or not (723) [without multiple writes to](https://github.com/commaai/panda/blob/d56bad2b7f2309e7490720b3b32341de9644096a/board/stm32h7/clock.h#L22) `PWR->CR3`, and this appears to be the only real difference between the two.
This detection is based on the package type, which is nicely exposed in `SYSCFG->PKGR`. This does mean we can't have any overlap between 723 and 725 /735 packages in future designs, but it's unlikely we'll need to.
> Detect H723 in firmware

- __init__.py
Needed for https://github.com/commaai/opendbc/pull/1049, so that both opendbc CI (pip package) and openpilot (submodule) can import uds and isotp properly. `panda.python` isn't available in the pip package, but everything defined in this file is.
> make uds and isotp general imports

- python/__init__.py
- tests/can_printer.py
~~I was struggling to get canbus 3 (aka canbus 1 in obd mode) to print anything when I had only 1 other node connected on the CAN.~~  
~~I don't fully understand what is going on, but `can_reset_communications()` but it seems to help to at least show few messages, before it stops.~~
Print CAN3.
> Enable CAN3 printer

- board/debug/debug_h7.sh
- board/gdb.sh
- drivers/spi/load.sh
- drivers/spi/pull-src.sh
- release/make_release.sh
- tests/ci_shell.sh
- tests/hitl/run_parallel_tests.sh
- tests/hitl/run_serial_tests.sh
- tests/misra/install.sh
- tests/misra/test_misra.sh
- tests/read_st_flash.sh
- tests/setup_device_ci.sh
- tests/som_debug.sh
Mostly for macOS.
A good explaination [here](https://stackoverflow.com/a/58494728/639708).
Needed this to run `som_debug.sh` on macOS, but decided to update all scripts.
Same thing for:
- openpilot https://github.com/commaai/openpilot/pull/33111
- agnos-builder https://github.com/commaai/agnos-builder/pull/268
> update bash scripts to #!/usr/bin/env bash

- board/drivers/bxcan.h
- board/drivers/fdcan.h
- board/main.c
fdcan: log lost tx messages when resetting can core for multiplexing and can core reset
bxcan: log can core reset
follow up to https://github.com/commaai/panda/pull/1967
> drivers: log can core reset when switching multiplexing

- python/ccp.py
It was under "TODO" in python/ccp.py to define types for couple of function returns.
> Defining types in return dictionaries

- tests/misra/checkers.txt
- tests/misra/install.sh
Checkers diff:
```
diff --git a/tests/misra/checkers.txt b/tests/misra/checkers.txt
index a9cc721..00160a5 100644
--- a/tests/misra/checkers.txt
+++ b/tests/misra/checkers.txt
@@ -146,6 +146,7 @@ Yes  CheckOther::clarifyCalculation
Yes  CheckOther::clarifyStatement
Yes  CheckOther::invalidPointerCast
Yes  CheckOther::redundantBitwiseOperationInSwitch
+Yes  CheckOther::suspiciousFloatingPointCast
No   CheckOther::warningOldStylePointerCast                    require:style,c++
No   CheckPostfixOperator::postfixOperator                     require:performance
Yes  CheckSizeof::checkSizeofForArrayParameter
@@ -222,6 +223,27 @@ Not available, Cppcheck Premium is not used
Misra C 2012
------------
+No   Misra C 2012: Dir 1.1
+No   Misra C 2012: Dir 2.1
+No   Misra C 2012: Dir 3.1
+No   Misra C …
```
> misra: bump to cppcheck 2.15.0

- .github/workflows/test.yaml
- pyproject.toml
Makes `test_mutation.py` 3x faster when run locally:
```
real    3m0.221s
user    25m4.861s
sys     1m2.424s
vs
real    1m7.962s
user    8m0.304s
sys     0m33.491s
```
This is due to naming of `test_misra.sh`.  It was executed by pytest workers on their respective workpsace copy. They were compiling cppcheck and running all misra tests during test collection phase.
> fix test_mutation.py performace

- python/__init__.py
Panda needed more time to be detected by USB host after reset.
USB errors would would show for the devices with USB hubs.
> Fix USB errors

- board/can_comms.h
- board/drivers/spi.h
- board/main_comms.h
- tests/misra/suppressions.txt
Casting to uint8_t is a good solution given the nature of the structs we are copying to/from:
`can_health_t` is packed so it is fine to consider it an array of uint8_t
`ControlPacket_t` is packed so it is fine to consider it an array of uint8_t + trying to set each fields manually will make assumptions about endianness (since some `ControlPacket_t` elements are uint16_t and the buffer elements are uint8_t)
`CANPacket_t` is mostly a bit field struct that would require getting each fields manually with bit-wise operations and make assumptions about the order of the bits in the struct. But since it is also a packed struct, it is fine to just assume an array of uint8_t and proceed as before.
> misra21.15

- board/flasher.h
- board/safety/safety_mazda.h
- board/safety/safety_subaru.h
- board/stm32f4/llbxcan_declarations.h
- board/stm32f4/llusb_declarations.h
- board/stm32f4/stm32f4_config.h
- board/stm32h7/llfdcan_declarations.h
- board/stm32h7/llusb_declarations.h
- board/stm32h7/stm32h7_config.h
cppcheck does not work well for Misra2.5 for 2 reasons:
1. It will flag `SOMETHING` as unused when `CANFD` is not defined in the following example:
```c
#ifdef CANFD
#define SOMETHING
#endif
...
#ifdef CANFD
use SOMETHING
#endif
```
2. It will also consider a macro declared in a file included behing `#ifdef...` (even if the condition is false) but it will not check for usages of that macro in that file if the condition is false, making that macro a violation of Misra2.5
Because of that we won't be able to fix all Misra2.5 right now
> misra2.5: safety modes + stm32*

- board/can.h
- board/can_declarations.h
In `c++`, const have internal linkage by default. In `c`, const have external linkage by default.
We recently switched to explicitly declaring `PANDA_CAN_CNT` with external linkage (with the `extern` keyword) in order to comply with misra8.4. This does not affect anything in panda, since again in `c` const have external linkage by default and panda is a `c` project.
Because we are still defining variable in header (`PANDA_CAN_CNT` in `can.h`) and declaring them with external linkage now, we get redefinition errors when compiling pandad in openpilot because `can.h` is included in multiple translation units (`pandad.cc`, `main.cc`). This was not a problem before since pandad is a `c++` process, which mean that all those variables were already declared with internal linkage.
> Fix openpilot build

- board/safety.h
- tests/safety/mutation.sh
We will now mutate with all of these:
```
cxx_add_assign_to_sub_assign
Replaces += with -=
cxx_add_to_sub
Replaces + with -
cxx_and_assign_to_or_assign
Replaces &= with |=
cxx_and_to_or
Replaces & with |
cxx_assign_const
Replaces ‘a = b’ with ‘a = 42’
cxx_bitwise_not_to_noop
Replaces ~x with x
cxx_div_assign_to_mul_assign
Replaces /= with *=
cxx_div_to_mul
Replaces / with *
cxx_eq_to_ne
Replaces == with !=
cxx_ge_to_gt
Replaces >= with >
cxx_ge_to_lt
Replaces >= with <
cxx_gt_to_ge
Replaces > with >=
cxx_gt_to_le
Replaces > with <=
cxx_init_const
Replaces ‘T a = b’ with ‘T a = 42’
cxx_le_to_gt
Replaces <= with >
cxx_le_to_lt
Replaces <= with <
cxx_logical_and_to_or
Replaces && with ||
cxx_logical_or_to_and
Replaces || with &&
cxx_lshift_assign_to_rshift_assign
Replaces <<= with >>= …
```
> mutation tests: activate all mutation ops

- tests/safety/mutation.sh
We are currently missing 2 ops group:
`cxx_const_assignment` is buggy in our code base, will need to open an issue 
`cxx_logical` is known to be buggy: https://github.com/mull-project/mull/issues/994
> mutation test: add more ops

- python/__init__.py
- `flash: already up to date` was not showing up when running `flash.py`
- other messages can be `info` since they are normal flashing sequence
> use logger info for flashing

- python/__init__.py
Current implementation could potentially result in an endless loop, which cannot be caught or handled from outside the function.
> Remove retry loop 

- .github/workflows/test.yaml
- board/safety/safety_chrysler.h
test build + fix current release mode build
> ci: test building in release mode

- board/boards/tres.h
- board/drivers/fake_siren.h
- board/main.c
- board/stm32h7/lli2c.h
- python/__init__.py
from https://github.com/commaai/openpilot/issues/33814
If there's contention on the I2C (such as the 845 trying to config the amp), the fake siren init hangs forever in `i2c_status_wait` since the microsecond timer isn't initialized yet. Also fixes the panda leaving the bus in a bad state if the read fails.
> tres: fix I2C hang on fake siren init

- python/socketpanda.py
Panda class substitute for socketcan device (to support using the uds/iso-tp/xcp/ccp library)
> SocketPanda python library

- python/spi.py
```
comma@comma-863276c1:/data/openpilot/panda$ python -c "from panda import PandaDFU; print(PandaDFU(None)._handle.get_bootloader_id())"
b'\x93'
```
> spi: add helper for getting bootloader ID

- board/safety/safety_tesla.h
- tests/safety/test_tesla.py
- match `vehicle_moving` signal with opendbc Implementation
- allow cancel if openpilot Longitudinal Control is not enabled
> Tesla: Panda safety update

- tests/misra/test_misra.sh
simple fix to be able to run misra with macos's default bash and it should have no impact on linux / unix
> test: Allow running test_misra.sh easy on macos

- Dockerfile
**Description**
- **Updated Dependency Reference**: Updated `OPENDBC_REF` to a new commit hash (https://github.com/commaai/opendbc/commit/551081b32f4c1a76537ad2c777571ef5b93a849c) to use the latest version of the `commaai/opendbc` repository.
- **Fix in Symlink Creation Order**: Adjusted the sequence so that the symbolic link to the `opendbc` directory is created before running the `scons` build process, resolving potential setup or reference issues
- Bug introduced in https://github.com/commaai/opendbc/pull/1519
- Issue: https://github.com/commaai/panda/pull/2102
- **Improved Build Process**: Ensured the build commands (`scons`) work more reliably by properly referencing the `opendbc` symlink beforehand.
> Dockerfile: opendbc: symlink fix and use the latest ref

- board/main.c
Fixes the case where you're engaged -> park -> unplug device all in <30s. Not sure why we chose 30s initially, but 5s is more than enough.
> Reduce heartbeat beeper false positives

- Dockerfile
- examples/query_fw_versions.py
- tests/safety/test_toyota.py
**Description**
The generated DBC file used for Toyota SecOC platforms has been updated with the latest name.
This PR:
- Pointed the opendbc ref to the latest on [`commaai/opendbc`](https://github.com/commaai/opendbc)
- Updated `test_toyota.py` with the up-to-date generated DBC file name.
> Dockerfile: opendbc: small fixes and use the latest ref

- board/safety/safety_ford.h
- tests/safety/test_ford.py
For https://github.com/commaai/openpilot/issues/33944
> Ford: long safety is default for CAN

- board/drivers/fdcan.h
Closes https://github.com/commaai/panda/issues/2132 and https://github.com/commaai/openpilot/issues/33840.
Ignition off w/ canState1 and canState2 active receiving messages w/ forced resetting on canState0 (bus 2, similar case to right after ignition off in https://github.com/commaai/openpilot/issues/33840):
- No resetting: 0.13 interrupt load
- Resetting at 10Hz: 0.15 interrupt load (**this PR**)
- Resetting at 100Hz: 0.35 interrupt load
- Resetting w/o restrictions (~286Hz): 0.8 interrupt load (**similar to issue**)
> fdcan: rate limit CAN core reset

- board/drivers/can_common.h
`VCFRONT_vehiclePowerState`:
- Upon opening door -> `VEHICLE_POWER_STATE_ACCESSORY`=2
- Upon sitting in seat and closing door -> no change
- Upon depressing brake pedal -> `VEHICLE_POWER_STATE_DRIVE`=3
- Upon going into park (after driving) -> no change
- Upon getting out of seat with door open -> `VEHICLE_POWER_STATE_CONDITIONING`=1
I assume after a few minutes it goes into `VEHICLE_POWER_STATE_OFF`=0
> Tesla: update ignition signal for Model 3/Y

- board/drivers/can_common.h
We should verify that again. 
`ESPiB1_IgnitionOn` also sounds good.
I can't remember why I used this signal back then.
> Rivian: add CAN ignition

- board/drivers/can_common.h
> Fix Rivian ignition

- README.md
Update udev rules to fix various permission-related problems that users may encounter. Matches the rules set up by openpilot. This should probably move to a shared setup script someday.
Ideally the Panda and PandaDFU classes should provide better exceptions, but that's a project for another day.
Background:
* commaai/openpilot#34632
* commaai/openpilot#34674
> Update udev rules in README

- board/crc.h
- board/drivers/gpio.h
- board/flasher.h
- board/stm32f4/peripherals.h
- board/stm32h7/peripherals.h
For https://github.com/commaai/panda/issues/2171.
Add guards around platform/target-specific code. This way we won't have add cpp rule supression later.
> Add guards around platform-specific code

- tests/libpanda/SConscript
resolves: https://github.com/commaai/openpilot/issues/35093
special handling was added for mac to resolve gcc (internally, clang) to the actual GNU compiler (resolved as gcc-<ver> with brew): https://github.com/commaai/panda/pull/1241
with a recent update to MacOS (some time near 15.4), `gcc` was broken.
upon checking, clang17 supports `-std=gnu11`, which was the original complaint. as well, builds just fine. but there are still issues with building on less than 15 with clang.
using gcc on less than 15.
```
-- with .app --
➜ clang --version
Apple clang version 17.0.0 (clang-1700.0.13.3)
Target: arm64-apple-darwin24.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
-- with default CommandLineTools version, also …
```
> fix(macos): macOS 15 and greater

- SConstruct
> [!NOTE]
> Sister PRs: 
> * https://github.com/commaai/opendbc/pull/2428
> * https://github.com/commaai/openpilot/pull/35629
This brings the `compilation_db` functionality to **panda**, similar to what we already have in **openpilot**, which helps with IDE integration and code navigation.
_This feature was originally introduced in openpilot via [commaai/openpilot#19533](https://github.com/commaai/openpilot/pull/19533) by @adeebshihadeh._
Previously, the behavior in panda required the `--compile-db` flag to generate `compile_commands.json`. We've now improved this:
- **`compile_commands.json` is now always generated**—no need to pass a flag.
- Whether you build panda standalone or as part of openpilot, the compilation database is created automatically.
1. **Standalone Build**  
When …
> Add support for generating clang compilation database by default

- board/drivers/spi.h
- board/drivers/spi_declarations.h
- board/health.h
- board/main_comms.h
Checksums are just one of the things this is used to track; these end up mostly being mismatches in the SPI state machine.
> SPI: spi_error_count is a better name

- board/main.c
- board/stm32h7/lladc.h
- board/stm32h7/lladc_declarations.h
- board/stm32h7/peripherals.h
You can calibrate the VDDA reference voltage based on the internal reference voltage source. This improves measurement accuracy to at least <1% absolute error
> ADC VDDA calibration

- board/drivers/can_common.h
- board/drivers/can_common_declarations.h
Resolves https://github.com/commaai/panda/issues/2256
> Reset CANFD auto-detection on CAN init

- python/__init__.py
Added some debugging to the SPI driver, and this caused `scripts/debug_console.py` to loop infinitely on the read since every read generated new messages.
> fix infinite serial read
