commaai/panda

board/get_sdk.sh
board/tools/enter_download_mode.py

Added dependencies to get_sdk.sh. Cleaned up code in enter_download_m…ode.py and made compatible with py2 and py3.

Clean up download mode script and add dependency to installer.

---

board/usb.h

Commented on fields in USB protocol headers.
Replaced key values with DEFINE names for clarity on function.
Removed trailing whitespace in usb.h

Reformatted usb descriptor table for readability.

---

board/usb.h
panda/__init__.py

This patch should not be merged until a satisfactory driver is available.
This patch relies on the (Reformatted usb descriptor table for readability. #12).

Usb bulk to interrupt

---

board/build.mk
board/can.h
board/config.h
board/early.c
board/early.h
board/gpio.h
board/libc.h
board/llgpio.c
board/llgpio.h
board/main.c
drivers/linux/panda.c
panda/__init__.py
tests/debug_console.py
tests/loopback_test.py

Detect REV C boards and repair important tests.
Fix missing acknowledgement in Linux driver

Detect revc

---

board/gpio.c
board/main.c

- CAN3 is not available for legacy board.
- Minor stylecop.

Fix legacy board build

---

board/can.h
board/config.h
board/main.c
panda/__init__.py

Useful for board tests, customer troubleshooting, and linux driver loopback support.

Can loopback now runtime configurable.

---

__init__.py
board/build.mk
board/drivers/can.h
board/drivers/spi.h
board/drivers/usb.h
board/main.c
board/safety/safety_honda.h
boardesp/proxy.c
drivers/linux/Makefile
drivers/linux/README.md
drivers/linux/dkms.conf
panda/__init__.py
run_automated_tests.sh
tests/automated/0_builds.py
tests/automated/2_usb_to_can.py
tests/automated/4_wifi_functionality.py
tests/automated/5_wifi_udp.py
tests/automated/helpers.py
tests/loopback_test.py

This will add dkms support, and make installations easier. Especially
when upgrading the system from one kernel version to another. DKMS will
handle kernel upgrades automatically.

Add DKMS support

---

UPDATING.md

Small document on how to update the panda if it's not working through Chffr.

Add a small UPDATING.md

---

board/safety.h
board/safety/safety_honda.h

Switching to "rising edge" cancellation type, to allow the enabling when: 
- gas pedal is pressed
- brake pedal is pressed and speed is zero

Pre enable

---

board/safety.h
board/safety/safety_toyota.h

Adding a speed dependent steer torque limitation

Toyota torque limit

---

board/main.c

The REVB boards have a different voltage divider leading up to the ADC. When left uncompensated, a panda may appear to report 5V when in reality it is reading 12V, or vice versa.
Previously, health reported the raw output of the ADC. Now, voltage is reported in millivolts.
Math included in comments to deal with introduction of 'magic numbers'.

board: standardized how health voltage is reported between revisions.

---

examples/can_logger.py

Logs on all 3 CAN busses to output.csv

Adding a .csv CAN logger example

---

examples/can_unique.md
examples/can_unique.py

Given an interesting CSV file of CAN messages and a list of background CAN messages, print which bits in the interesting file have never appeared in the background files.

tool to reverse engineer a single bit field

---

README.md
board/README
board/README.md
board/get_mac_sdk.sh
boardesp/README.md

Details on installing on mac and readme updates

Adds Mac-specific instructions for setting up board and esp

---

board/drivers/usb.h

This removes the need to manually install the WinUSB driver on windows for Windows 8 and above.
For some reason on my machine I have to plug it in twice to get it to show up as a device named "panda".  Kind of strange, but not a huge deal, and not sure if this is specific to my Windows 10 machine.

auto-install WinUSB device driver

---

examples/can_bit_transition.md
examples/can_bit_transition.py

This script is really helpful for finding single bit on/off signals.  I used this script to find a brake pedal signal (see markdown file for more details).

Script to find bits that transition from always 0 to always 1

---

board/get_sdk.sh
board/get_sdk_mac.sh

get_sdk.sh and get_sdk_mac.sh are missing the python packages pycrypto and requests

get_sdk scripts missing packages

---

examples/can_bit_transition.py
examples/can_unique.py

add support for multiple buses to can_unique and can_bit_transition

---

board/drivers/can.h
board/drivers/uart.h
board/main.c

Currently this attempts to initialize at 500, 250, 125 kbps.  Should any other speeds be included?

Bounty: panda high quality CAN autobaud

---

examples/tesla_tester.py

Replaces a counter with a check of the dictionary contents to work around a potential bug: if the same VIN piece were received twice, it would still have incremented the counter.

Strengthen Tesla VIN detection

---

board/safety/safety_gm.h

If LKA camera is still connected to powertrain.

GM: passive on LKA-only cars

---

board/safety.h
board/safety/safety_subaru.h

Bus 0 to 1
Bus 1 to 0 except LKA message

Subaru: Forwarding

---

board/build.mk
board/gpio.h
board/main.c
common/version.mk
python/__init__.py
python/update.py

This PR removes DCP mode when EON builds panda code. It avoids entering in DCP mode when EON takes long time to boot.

Dcp remove

---

board/gpio.h
board/main.c
python/__init__.py

Power Saving

---

setup.py

libusb1 versions >1.6.6 do not work

fix usb flashing

---

examples/query_vin_and_stats.py

Fix query_vin_and_status.py require python 3.7

---

.circleci/config.yml
board/Makefile.strict
board/drivers/can.h
board/main.c
tests/build_strict/Dockerfile
tests/misra/Dockerfile
tests/misra/test_misra.sh

Added misra-c 2012 test and fixes few violations.
Also added -pedantic flag in Makefile to highlight build warnings.
Goal is to get zero misra violations and zero compiler warnings.

Misra c2012

---

board/safety.h
board/safety/safety_chrysler.h
board/safety/safety_elm327.h
board/safety/safety_ford.h
board/safety/safety_gm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_subaru.h
board/safety/safety_tesla.h
board/safety/safety_toyota.h
board/safety/safety_toyota_ipas.h
board/safety_declarations.h
tests/safety/libpandasafety_py.py
tests/safety/test.c

The controlling expression of an if statement and the controlling expression of an iteration‑statement shall have essentially Boolean type

Misra 14.4 violations

---

board/safety.h
board/safety/safety_chrysler.h
board/safety/safety_gm.h
board/safety/safety_tesla.h

Operands shall not be of inappropriate essential type

Misra 10.1

---

board/safety/safety_cadillac.h
board/safety/safety_chrysler.h
board/safety/safety_elm327.h
board/safety/safety_ford.h
board/safety/safety_gm.h
board/safety/safety_gm_ascm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_subaru.h
board/safety/safety_tesla.h
board/safety/safety_toyota.h
board/safety/safety_toyota_ipas.h
board/safety_declarations.h

Also standardize addr type to int

Make macros to get msg attributes

---

board/safety/safety_cadillac.h
board/safety/safety_chrysler.h
board/safety/safety_ford.h
board/safety/safety_gm.h
board/safety/safety_gm_ascm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_subaru.h
board/safety/safety_tesla.h
board/safety/safety_toyota.h

`An "if... else if" statement shall always be terminated with an "else".`
Avoided blank `else` statements.

Misra 15 7

---

.circleci/config.yml
board/drivers/adc.h
board/drivers/can.h
board/drivers/clock.h
board/drivers/gmlan_alt.h
board/drivers/llgpio.h
board/drivers/spi.h
board/drivers/uart.h
board/drivers/usb.h
board/gpio.h
board/libc.h
board/main.c
board/power_saving.h
board/safety/safety_cadillac.h
board/safety/safety_chrysler.h
board/safety/safety_defaults.h
board/safety/safety_gm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_tesla.h
board/safety_declarations.h
tests/build_strict/test_build_strict.sh
tests/safety/test.c

Strict compiler

---

board/bootstub.c
board/drivers/can.h
board/drivers/usb.h
board/gpio.h
board/main.c
board/pedal/main.c

Every switch statement shall have a default label

Misra 16_4: every switch statement shall have a default label

---

board/main.c

The body of an iteration‑statement or a selection‑statement shall be a compound‑statement

Misra 15_6: The body of an iteration‑statement or a selection‑statement shall be a compound‑statement

---

board/drivers/gmlan_alt.h
board/drivers/uart.h

Misra 17.8: a function parameter should not be modified

---

board/Makefile
board/drivers/llcan.h
board/drivers/usb.h
board/main.c
board/pedal/Makefile
board/pedal/main.c
board/provision.h
board/safety/safety_cadillac.h
board/safety/safety_chrysler.h
board/safety/safety_ford.h
board/safety/safety_gm.h
board/safety/safety_gm_ascm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_subaru.h
board/safety/safety_tesla.h
board/safety/safety_toyota.h
board/safety/safety_toyota_ipas.h
board/safety_declarations.h
board/spi_flasher.h
tests/misra/suppressions.txt
tests/misra/test_misra.sh
tests/safety/libpandasafety_py.py
tests/safety/test.c
tests/safety/test_honda.py

Also replace CAN byte manipulation with GET-BYTE macro

Misra 11.x: pointer usage.

---

boardesp/get_sdk.sh
boardesp/get_sdk_ci.sh
boardesp/get_sdk_mac.sh
boardesp/python2_make.py
tests/build/Dockerfile

seems a ugly fix, but it works

Fix sdk build in python3 env

---

board/main.c
python/__init__.py
tests/automated/1_program.py

I want to reflash the panda based on signature mismatch instead of version numbers we can forget to increase. This PR adds panda support to read the 128 byte RSA signature at the end of the code section

Command to get signature

---

board/bootstub.c
board/main.c
board/spi_flasher.h
crypto/sign.py

I didn't test this, but I think it corresponds to what we discussed yesterday.

security upgrades

---

board/main.c

Needed changes for issue commaai/openpilot#1005.
Needs changes in boardd too to make sure that they turn off when ignition goes low

Added the option to turn on IR in power savings mode

---

board/safety/safety_toyota.h
tests/safety/test_toyota.py

To poll the blind spot sensor 0x750 is required

Add the ability to communicate with BSM

---

board/safety.h
board/safety/safety_volkswagen.h
board/safety_declarations.h
requirements.txt
tests/safety/libpandasafety_py.py
tests/safety/test.c
tests/safety/test_volkswagen_mqb.py

Second of roughly three PRs to review the overall change set proposed in #443.
- German Engineered™ CRC and counter validation for all applicable messages (#411)
- Added standstill check and brake in motion safety check (#441)
- Six new safety unit tests

Volkswagen safety updates: Phase 2

---

board/crc.h
board/pedal/main.c

abstract crc function

---

board/safety/safety_chrysler.h
board/safety/safety_ford.h
board/safety/safety_gm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_nissan.h
board/safety/safety_subaru.h
board/safety/safety_toyota.h
tests/safety/test_chrysler.py
tests/safety/test_gm.py
tests/safety/test_honda.py
tests/safety/test_hyundai.py
tests/safety/test_nissan.py
tests/safety/test_subaru.py
tests/safety/test_toyota.py

UNSAFE_DISABLE_DISENGAGE_ON_GAS (all cars)
UNSAFE_RAISE_LONGITUDINAL_LIMITS_TO_ISO_MAX (toyota)

add unsafe gas/long limit checks to safety.

---

board/drivers/usb.h

https://github.com/commaai/panda/pull/421#discussion_r369969662

Fixed possible race condition

---

tests/safety/common.py
tests/safety/test_toyota.py
tests/safety/test_volkswagen_mqb.py

also added the following to PandaSafetyTest
* `test_prev_brake`
* `test_enable_control_allowed_from_cruise`
* `test_disable_control_allowed_from_cruise`

Safety Test Refactor: Volkswagen MQB

---

board/safety/safety_hyundai.h
tests/safety/test_hyundai.py
tests/safety_replay/test_safety_replay.py

Hyundai-Kia-Genesis (HKG)

---

board/safety/safety_honda.h
board/safety/safety_toyota.h
board/safety_declarations.h
tests/safety/common.py
tests/safety/test_honda.py
tests/safety/test_toyota.py

* Made pedal calculation brand-specific
* Fixed Toyota pedal calculations
* Re-calculated limits based on OP limits + 5%

Pedal gas pressed safety limits

---

board/safety/safety_chrysler.h
board/safety/safety_gm.h
board/safety/safety_hyundai.h
board/safety/safety_mazda.h
board/safety/safety_subaru.h
board/safety/safety_toyota.h
board/safety/safety_volkswagen.h
board/safety_declarations.h
tests/safety/libpandasafety_py.py
tests/safety/test.c
tests/safety/test_chrysler.py
tests/safety/test_gm.py
tests/safety/test_hyundai.py
tests/safety/test_subaru.py
tests/safety/test_toyota.py
tests/safety/test_volkswagen_mqb.py
tests/safety/test_volkswagen_pq.py

Next step is common set of tests for torque-based safety modes

Make torque-based steering state global

---

board/drivers/can.h

FCA fix PR #524: internal CI run

---

.circleci/config.yml

Seems like CircleCI isn't offering docker layer caching in the free plan anymore

Disable docker layer caching

---

board/safety/safety_mazda.h
tests/safety/test_mazda.py

Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

Mazda: safety tests add missing safety checks

---

board/safety/safety_nissan.h

Fix leaf brake rx check

---

board/build.mk
board/libc.h
board/main.c

Not sure why it broke with the old code yet, the logic and assembly seem to be fine. It's optimized in a different way, but doesn't look broken in any obvious way.

Fix new compiler bug

---

.pre-commit-config.yaml
board/drivers/llcan.h
board/drivers/rtc.h
board/drivers/uart.h
board/inc/cmsis_gcc.h
board/inc/mpu_armv7.h
board/pedal/Makefile
board/power_saving.h
board/safety/safety_toyota.h
docs/panda_wifi_setup.md
drivers/windows/panda_playground/ReadMe.txt
tests/misra/coverage_table

* remove irrelevant checks
* don't allow commits with merge conflicts
* don't allow commits with symlinks that don't point anywhere
* trim trailing whitespace

Add pre-commit hooks

---

board/drivers/usb.h
board/main.c
tests/gmlan_harness_test.py

Mainly to combat overheating of C2s when building/booting

Turn on fan if panda is enumerated but not receiving heartbeat

---

board/drivers/uart.h
board/main.c
python/__init__.py

get k-line working again and update wakeup for KWP2000

K line fix

---

board/get_sdk.sh
board/get_sdk_mac.sh
requirements.txt
setup.py
tests/build/Dockerfile.panda_esp

This PR replaces pycrypto with currently maintained fork pycryptodome https://pypi.org/project/pycryptodome/

Replace pycrypto with pycryptodome

---

board/safety/safety_nissan.h
tests/safety/test_nissan.py

@adeebshihadeh Updating gas pressed threshold in panda as requested in commaai/openpilot#1995

Updating X-Trail/Rogue gas_pressed threshold

---

board/boards/uno.h

To fix commaai/openpilot#2493
Pretty sure this doesn't really save much power on the C2 anyways

Don't turn off the phone power on C2 when changing USB mode

---

board/safety/safety_nissan.h

Port for Nissan Altima. This one was a little different as the EPS is on a different CAN bus, requires minor changes to the wiring harness. I'll submit the openpilot PR once this has been merged.
```
Rogue/X-Trail:
(C-CAN)   (V-CAN)
|       |
|       |
|       - CAN (0)
(1) CAM -       
|       - ADAS (2)
|       |
|       |
(ADAS UNIT)
Altima:
(C-CAN)   (V-CAN)
|       |
|       |
(0) CAN -       |
- CAM (1)
(2) ADAS -       |
|       |
|       |
(ADAS UNIT)
```

Nissan Altima port

---

board/boards/common.h
board/drivers/gmlan_alt.h

Move gmlan_alt to TIM12 to fix concurrency issue with IR PWM

---

board/safety/safety_hyundai.h
tests/safety/test_hyundai.py

note that they excluded the counter from the checksum

hyundai: WHL_SPD11 checksum

---

Dockerfile.panda
board/safety/safety_hyundai.h
tests/safety/test_honda.py
tests/safety/test_hyundai.py

Goes with https://github.com/commaai/openpilot/pull/21147

Hyundai: add gas pressed signal for hybrids

---

Dockerfile.panda
board/crc.h
board/drivers/can.h
board/drivers/interrupts.h
board/drivers/llcan.h
board/drivers/registers.h
board/drivers/uart.h
board/drivers/usb.h
board/gpio.h
board/pedal/main.c
board/power_saving.h
board/safety/safety_chrysler.h
board/safety/safety_gm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_mazda.h
board/safety/safety_nissan.h
board/safety/safety_subaru.h
board/safety/safety_toyota.h
board/safety/safety_volkswagen.h
board/safety_declarations.h
tests/misra/suppressions.txt

Updated cppcheck and misra to the latest, suppressed inline new violations, will fix with next PRs.

Update cppcheck and misra, suppress for now

---

Dockerfile.panda
board/drivers/can.h
board/drivers/uart.h
board/drivers/usb.h
board/main.c

Update cppcheck with the latest upstream and fix legit 8.2 violations

Fix MISRA 8.2 violations

---

board/pedal/main.c
python/__init__.py

Add hw check support to pedal code and panda library

Add pedal check to panda lib

---

board/pedal/main.c
board/stm32fx/lldac.h
board/stm32fx/stm32fx_config.h

Move dac.h to HAL

---

board/drivers/timers.h
board/safety.h
board/safety/safety_chrysler.h
board/safety/safety_gm.h
board/safety/safety_hyundai.h
board/safety/safety_mazda.h
board/safety/safety_subaru.h
board/safety/safety_toyota.h
board/safety/safety_volkswagen.h
tests/safety/test.c

Abstract MICROSECOND_TIMER

---

board/bootstub.c
board/flasher.h
board/stm32fx/llflash.h
board/stm32fx/peripherals.h
board/stm32fx/stm32fx_config.h

Refactor flasher.h (previously spi_flasher.h)

Refactor flasher

---

board/drivers/uart.h
board/stm32fx/lluart.h

uart.h refactor #2

---

board/safety/safety_honda.h
tests/safety/common.py
tests/safety/test_honda.py
tests/safety_replay/helpers.py

This reverts commit 46593af6190a09aea8a1a734e6b3cdcd4227cb98.

Revert "Honda Bosch: Support extended LKAS_HUD IDs (#615)"

---

board/main.c
board/safety.h
board/safety/safety_chrysler.h
board/safety/safety_defaults.h
board/safety/safety_gm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_mazda.h
board/safety/safety_nissan.h
board/safety/safety_subaru.h
board/safety/safety_tesla.h
board/safety/safety_toyota.h
board/safety/safety_volkswagen.h
board/safety_declarations.h

support using safety mode param to control rx checks 

---

board/safety/safety_hyundai.h
python/__init__.py
tests/safety/test_honda.py
tests/safety/test_hyundai.py

continuation of https://github.com/commaai/panda/pull/616

Hyundai longitudinal

---

examples/query_fw_versions.py
python/uds.py

finish #699 @martinl @jyoung8607 can you test?

UDS: add response pending timeout

---

.github/workflows/test.yaml

This PR updates misra test artifacts upload workflow, tests/misra/test_misra.sh outputs separate files for f4, h7 and pedal

Misra artifacts upload

---

Dockerfile.panda
tests/safety/test_volkswagen_pq.py

VW PQ: Refactor tests to use CAN packer

---

board/libc.h

Tested on my refactoring branch, works and adds ~5% to through output so I would like to merge it asap if nobody minds.

memcpy with 4 bytes support

---

python/__init__.py
tests/automated/4_can_loopback.py

Add message integrity test

---

board/config.h
board/main.c
python/__init__.py
tests/automated/1_program.py
tests/automated/helpers.py

Adds versioning to health packet structure and CAN/USB packet structure.

Check panda library and firmware for compatibility

---

board/drivers/bxcan.h
board/drivers/can_common.h
board/drivers/fdcan.h
board/main.c

refactor bus settings into bus_config struct

---

Dockerfile.panda
board/safety/safety_nissan.h
tests/safety/common.py
tests/safety/test_nissan.py

Nissan Leaf: tests + new brake signal

---

board/stm32h7/clock.h
board/stm32h7/llfdcan.h

With previous settings we do not support 5Mbit/s. Only 1, 2, 3, 6. With this settings 1,2,5 will be supported.

Change H7 CAN FD clocks to support both 2 and 5 Mbit/s

---

board/safety/safety_honda.h
board/safety_declarations.h
python/__init__.py
tests/safety/common.py
tests/safety/test_honda.py

Honda: handle ACC state consistent with ISO 15622:2018

---

board/drivers/can_common.h

Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

Mazda: Fix CX-5 ignition

---

board/safety/safety_chrysler.h
tests/safety/common.py
tests/safety/test_chrysler.py

Per our discussion in #824. Also carries over the brake rising edge cleanup.

Chrysler: remove standstill exception for gas disengage

---

board/boards/black.h

This has never worked... Drops power consumption in power save to 150mW

BP: fix gps enable pin

---

board/drivers/usb.h
board/main.c

This method is a lot more reliable than previous one(tested on BP and C3)

Reliable USB enumeration check

---

board/safety/safety_gm.h
tests/safety/test_gm.py

Moved from https://github.com/commaai/panda/pull/837

GM: change from brake threshold to Brake_Pressed bit

---

board/drivers/usb.h

Fix USB enumeration detection for C2

Fix USB enumeration detection for C2

---

board/safety/safety_honda.h
tests/safety/test_honda.py

Resolves: https://github.com/commaai/panda/issues/888

Honda Nidec: ACC_HUD safety

---

board/safety.h
board/safety/safety_body.h
board/safety/safety_chrysler.h
board/safety/safety_defaults.h
board/safety/safety_gm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_mazda.h
board/safety/safety_nissan.h
board/safety/safety_subaru.h
board/safety/safety_tesla.h
board/safety/safety_toyota.h
board/safety/safety_volkswagen_mqb.h
board/safety/safety_volkswagen_pq.h

safety: move controls_allowed and relay malfunction reset

---

board/safety/safety_gm.h
tests/safety/test_gm.py

This reverts commit 3bd3ae885ad1718e40aec0ead43b8ba4dba8e22c.
openpilot PR: https://github.com/commaai/openpilot/pull/24612

GM: revert back to brake threshold

---

board/safety/safety_honda.h

Remove duplicate word in comment

---

tests/pedal/canhandle.py

needed to handle can send errors

CAN flasher: add timeout to CanHandle on transmit

---

tests/safety/test_volkswagen_mqb.py

Harmonize with VW PQ and prep for #920: garbage-collect the manual COUNTER test code, now done natively in CANPacker.

VW MQB: Cleanup message counter handling

---

tests/canfd/test_canfd.py
tests/echo.py

cleanup heartbeat threads from scripts and test_canfd

---

python/__init__.py
tests/automated/helpers.py
tests/pedal/test_pedal.py

Serial length for real panda is always == 24

python lib: check serial length for Panda.list()

---

Jenkinsfile
tests/ci_reset_hw.py
tests/ci_resetter.py
tests/libs/resetter.py

Will reset all pandas in CI with DFU flash

CI: add hardware reflasher

---

python/__init__.py
tests/gmlan_harness_test.py
tests/gps_stability_test.py
tests/pedal/test_pedal.py

Think it was old plan to remove those

python lib: cleanup hw type check

---

board/drivers/fdcan.h

H7 will auto recover, no need for this.

H7: remove manual bus off handling

---

python/uds.py

IsoTpMessage: parameterize separation time

---

board/safety/safety_gm.h
tests/safety/test_gm.py

For PR: https://github.com/commaai/openpilot/pull/25970

GM: change brake pressed signal

---

tests/safety/test_toyota.py

This bit is extensively tested in common.py

Toyota: remove redundant test

---

board/drivers/can_common.h
board/drivers/fdcan.h
board/health.h
board/main_comms.h
board/stm32h7/llfdcan.h
python/__init__.py
tests/canfd/test_canfd.py

CAN-FD non-ISO support

---

tests/safety/test_hyundai.py

Introduced in https://github.com/commaai/opendbc/pull/656

Hyundai tests: fix counter in FCA message

---

board/safety/safety_gm.h
tests/safety/test_gm.py

For https://github.com/commaai/openpilot/pull/26197

Revert "GM: different brake thresholds by platform (#1104)"

---

tests/safety/test_gm.py

these addresses are not even allowed by the safety mode, we can just pass on them

GM Cam: pass on useless tests

---

tests/safety/common.py
tests/safety/test_hyundai_canfd.py

Tests HDA1 EV and HEV (previously only HEV)
Tests alt buttons EV and HEV (previously only HEV)
in the vein of https://github.com/commaai/panda/issues/1110

Hyundai CAN-FD: more complete tests

---

board/safety.h
board/safety/safety_honda.h
board/safety_declarations.h
tests/safety/test_honda.py

Less longitudinal_allowed references

Honda Nidec: max gas safety and common speed cmd checks

---

examples/query_fw_versions.py
python/__init__.py

improves the car port experience for those needing multiple pandas/external red panda
https://discord.com/channels/469524606043160576/539096103468007424/1022224299093921913

examples: choose panda for fw query

---

examples/query_fw_versions.py
python/__init__.py
tests/canfd/test_canfd.py
tests/ci_reset_hw.py
tests/hitl/1_program.py
tests/hitl/2_health.py
tests/hitl/helpers.py
tests/pedal/test_pedal.py

- Now also closes the panda when an exception occurs inside the context manager

Panda: context manager support

---

board/safety/safety_ford.h
tests/safety/test_ford.py

Just to assert the other signals aren't used

Ford: lateral motion control safety

---

python/usb.py

can't bump panda since this file is checked via following an import somewhere in OP

usb handle: ignore types

---

board/drivers/clock_source.h
board/drivers/timers.h
board/main_comms.h
board/stm32fx/clock.h
board/stm32fx/stm32fx_config.h
board/stm32h7/stm32h7_config.h
python/__init__.py
tests/hitl/2_health.py

@sshane noticed the microsecond timer is actually running as a half-microsecond timer

Microsecond timer fix

---

board/safety/safety_ford.h
tests/safety/test_ford.py

Pulled from https://github.com/commaai/panda/pull/1258 and https://github.com/commaai/panda/pull/1249

Ford: set vehicle speed and check counter

---

board/safety/safety_ford.h

Pulled from https://github.com/commaai/panda/pull/1258 and https://github.com/commaai/panda/pull/1249, like https://github.com/commaai/panda/pull/1261
Passes test models, no invalid addrs

Ford: check counter for yaw rate

---

board/safety/safety_ford.h

Checks checksums for rx messages added in https://github.com/commaai/panda/pull/1262 and https://github.com/commaai/panda/pull/1261

Ford: check checksums

---

board/safety.h
board/safety/safety_body.h
board/safety/safety_chrysler.h
board/safety/safety_ford.h
board/safety/safety_gm.h
board/safety/safety_honda.h
board/safety/safety_hyundai.h
board/safety/safety_hyundai_canfd.h
board/safety/safety_mazda.h
board/safety/safety_nissan.h
board/safety/safety_subaru.h
board/safety/safety_subaru_legacy.h
board/safety/safety_tesla.h
board/safety/safety_toyota.h
board/safety/safety_volkswagen_mqb.h
board/safety/safety_volkswagen_pq.h
board/safety_declarations.h
tests/libpanda/safety_helpers.h

Generically checks the quality flag signal for the yaw rate and speed signal to be used in the driver torque limiting PR: https://github.com/commaai/panda/pull/1249/files

Ford: check quality flag

---

python/__init__.py
python/dfu.py
tests/hitl/0_dfu.py

DFU HITL tests

---

board/drivers/fake_siren.h

Adjusted to match the new amp config https://github.com/commaai/openpilot/commit/75eaca3cf360614dcc86a7028921bbf022e30fa9

tres: adjust siren volume

---

python/__init__.py
requirements.txt
tests/hitl/0_dfu.py
tests/hitl/1_program.py
tests/hitl/2_health.py
tests/hitl/3_usb_to_can.py
tests/hitl/4_can_loopback.py
tests/hitl/5_gps.py
tests/hitl/6_safety.py
tests/hitl/conftest.py
tests/hitl/helpers.py
tests/hitl/test.sh

HITL tests: nose -> pytest

---

python/uds.py

According to https://en.wikipedia.org/wiki/ISO_15765-2, 4-15 are reserved frame codes. Throw exception if we receive a message with them

IsoTpMessage: check not reserved frame

---

board/safety/safety_tesla.h
tests/libpanda/safety_helpers.h
tests/safety/test_tesla.py

Tesla: move reading AEB state to RX hook

---

board/safety.h
board/safety/safety_ford.h
board/safety_declarations.h
tests/safety/test_ford.py

angle and curvature are linearly proportional, so we treat them as the same thing for ford. this makes the safety use one common function

safety: common angle safety function

---

tests/safety/test_ford.py

fairly clear what this does as a one liner

Ford: cleaner safety check

---

tests/safety_replay/test_safety_replay.py

Adds route for https://github.com/commaai/panda/pull/991

Subaru: add gen 2 Outback route

---

board/safety.h
board/safety/safety_ford.h
board/safety_declarations.h
tests/safety/test_ford.py

Ford safety: more clear variable names

---

tests/safety/test_ford.py

from https://github.com/commaai/panda/pull/1391
Ensures we can't send any of the other signals above and below the limit speed

Ford: test angle error speed in steering signal test

---

board/safety/safety_ford.h
tests/safety/test_ford.py

Similar to https://github.com/commaai/panda/blob/4b0427551412fd1ac4ca31d8aa376b090afb0435/tests/safety/common.py#L501 Will move to common angle tests once ford uses them

Ford: test angle measurement

---

board/drivers/fdcan.h
board/stm32h7/llfdcan.h

Revert "H7: fix lockup on disconnected bus"

---

board/drivers/bxcan.h
board/drivers/fdcan.h
board/stm32h7/llfdcan.h

H7: fix lockup on disconnected bus

---

board/drivers/uart.h
board/stm32fx/lluart.h
board/stm32h7/lluart.h

To make sure we don't lose the last logs coming from the SOM

UART overwrite mode

---

board/drivers/bxcan.h
board/drivers/fdcan.h
board/main_comms.h

Shouldn't be called on every interrupt but only with error interrupt or on request

Change can_health request method

---

board/drivers/spi.h
tests/hitl/8_spi.py

Allows listing/enumeration even if the protcols don't match

SPI: send serial with protocol version

---

board/safety/safety_toyota.h

tiny refactor from https://github.com/commaai/panda/pull/1189

safety_toyota: use GET_BIT

---

board/safety/safety_ford.h
board/safety_declarations.h

split from https://github.com/commaai/panda/pull/1189

angle safety: make angle conversion factor a float

---

board/safety/safety_ford.h

not sure if we want to add prefixes to the CAN MSG constants yet?

Ford: namespaced constants

---

board/drivers/gmlan_alt.h

H7: explicitly disable GMLAN for now

---

board/stm32h7/lladc.h

Do oversampling instead of longer sample times

Stable ADC on H7

---

board/safety/safety_subaru.h

couple small changes from my long PR to be similar to other brands

Subaru: cleanup panda logic

---

.github/workflows/test.yaml
board/drivers/gpio.h
board/jungle/boards/board_declarations.h
board/jungle/boards/board_v1.h
board/jungle/boards/board_v2.h
board/jungle/boards/unused_funcs.h
board/jungle/main.c

porting https://github.com/commaai/panda_jungle/pull/8

jungle: SBU provisioning tests

---

board/jungle/boards/board_v1.h
board/jungle/boards/board_v2.h

Imo should be also done to all pandas, multiplexing disturbs bus.

jungle: disable transceivers while doing CAN multiplexing

---

.pre-commit-config.yaml
README.md
examples/tesla_tester.py
pyproject.toml
requirements.txt
tests/elm_car_simulator.py
tests/safety/common.py
tests/safety/test_subaru.py

`pre-commit run --all` is now <1s

switch to ruff linter

---

tests/safety/test_gm.py

https://github.com/commaai/panda/pull/1573

GM: move more longitudinal related function into class

---

tests/safety/common.py

this function should be generic enough to be used for gas/brake, accel, and steering commands

Safety: generic limit safety check

---

tests/safety/common.py
tests/safety/test_subaru.py

split out torque and stock long into separate base classes in preparation for long and angle based controllers

Subaru: prepare tests for long and angle control

---

board/safety/safety_subaru.h
tests/safety/common.py
tests/safety/test_subaru.py

there are 2 static signals, and a high beam assist message that we need to emulate to keep the car happy when eyesight is disabled

Subaru: gen2 long safety

---

board/stm32fx/lluart.h

F4: fix UART clocks

---

tests/safety/test_chrysler.py
tests/safety/test_gm.py
tests/safety/test_hyundai.py

**Prerequisite of**
- https://github.com/commaai/panda/pull/1623

Safety tests: Convert message addresses from decimal to hexadecimal

---

board/safety/safety_nissan.h
tests/safety/common.py
tests/safety/test_nissan.py

Split from https://github.com/commaai/panda/pull/1649. We weren't testing this safety param

Nissan: test alternate EPS bus param

---

board/safety/safety_subaru.h
tests/safety/test_subaru.py

Similar to https://github.com/commaai/panda/pull/1680

Subaru: consider true angle sign in safety

---

drivers/linux/Makefile
drivers/linux/README.md
drivers/linux/panda.c

There are some good tools that support linux SocketCAN and because our driver was using interrupt mode it can't keep up heavy traffic on the CAN bus.  This should fix that issue and some other miscellaneous cleanup.

socketcan: usb bulk mode for rx

---

tests/safety_replay/helpers.py
tests/safety_replay/replay_drive.py

For https://github.com/commaai/panda/pull/1189

safety replay: support Toyota LTA angle control

---

board/safety/safety_hyundai.h
tests/safety/test_hyundai.py

Includes regen braking by user

Hyundai CAN: update driver braking signal

---

board/safety/safety_honda.h
board/safety/safety_toyota.h
tests/safety/common.py

Simpler version of https://github.com/commaai/panda/pull/1735, solves mismatch caught in https://github.com/commaai/openpilot/pull/30443

safety: check interceptor msg counter

---

.github/workflows/test.yaml
tests/misra/test_mutation.py

this is a prereq to doing lots more mutations

parallelize misra mutation tests

---

board/safety/safety_toyota.h
tests/safety/common.py
tests/safety/test_honda.py
tests/safety/test_toyota.py

exhibit A: https://github.com/commaai/panda/pull/1735/files#diff-83c369502a4fc7558b44769d6c11cbe0545991c7db422e70a5ddfd0af747422bR170

safety tests: rename gas interceptor test

---

Dockerfile
board/safety/safety_subaru.h
tests/safety/test_subaru.py

see https://github.com/commaai/opendbc/pull/995

Subaru: cruise_rpm and cruise_throttle are 13 bits

---

board/drivers/can_common.h
board/drivers/fdcan.h
board/drivers/gmlan_alt.h
board/drivers/harness.h
board/safety/safety_nissan.h
tests/misra/suppressions.txt

For [#1794](https://github.com/commaai/panda/issues/1794)

enable misra-c2012-10.4

---

tests/misra/suppressions.txt

Was fixed in #1802, missed removing the suppression in that PR

enable misra-c2012-8.6

---

board/drivers/spi.h
board/provision.h
tests/misra/suppressions.txt

This may not be the correct fix and not sure if there are negative side effects with these changes

enable misra-c2012-21.14

---

tests/misra/suppressions.txt

for #1794
Enabled with 5ddc0cf

enable misra-c2012-21.16

---

board/safety/safety_volkswagen_mqb.h

Verify CRC, counter, and frequency for the cruise control button message from the car.

VW MQB: RxChecks for GRA_ACC_01

---

board/safety/safety_toyota.h
tests/safety/test_toyota.py

Split from https://github.com/commaai/panda/pull/1611

Toyota: check ACC_CONTROL for relay malfunction

---

board/safety/safety_toyota.h
tests/safety/test_toyota.py

Split from https://github.com/commaai/panda/pull/1611

Toyota: longitudinal msgs behind safety param

---

board/boards/black.h
board/boards/dos.h
board/boards/red.h
board/boards/red_chiplet.h
board/boards/uno.h
board/bootstub_declarations.h
board/drivers/can_common.h
board/main.c
board/main_declarations.h
python/__init__.py
tests/hitl/9_harness.py

Adjust CAN bus orientation live with harness orientation

---

Dockerfile
pyproject.toml

fixed in 8.1.0. https://github.com/commaai/panda/pull/1864

pytest bugs are fixed

---

board/safety/safety_subaru.h
tests/safety/test_subaru.py

Feature parity for https://github.com/sunnypilot/panda/pull/20.
Will require another code change in the main OP repository to increase the RPM limit within the car interface.py.
I have been testing and daily driving my code changes (including RPM increase in the interface.py) for almost a week now. Have had zero issues.

Increase Subaru RPM limit

---

tests/misra/checkers.txt
tests/misra/test_misra.sh

Checker list is generated for each test run variant and appended to `checkers_report.txt`.
`checkers_report.txt` is then compared against `checkers.txt` in git.

Generate cppcheck checkers list

---

board/drivers/registers.h

remove void return

---

Jenkinsfile

tres and dos jungles could previously get into a bad state

jenkins: run jungles first

---

python/uds.py

caught by https://github.com/commaai/openpilot/pull/33156

missed a busTime

---

README.md

Very minor fix; Changed C++ library link to reflect boardd -> pandad change.

Update README.md to fix dead link

---

.gitignore
setup.py

Needs setuptools in the setup.py

fix python setup

---

Jenkinsfile
board/flash.py
board/jungle/flash.py
board/jungle/recover.py
board/recover.py
python/__init__.py

Makes it easier to work with multiple pandas attached - helps to avoid accidentally connecting to a wrong one.

Add multiple pandas selector

---

board/jungle/scripts/can_health.py
board/jungle/scripts/can_printer.py
board/jungle/scripts/spam_can.py
tests/can_health.py
tests/can_printer.py

- print all busses by default
- add colors for can_health
- scripts panda/jungle

CAN print improvement

---

board/safety/safety_ford.h
tests/safety/test_ford.py

Estimating the max EPS allowed rate using some old plots from last year:

Ford: higher curvature rate limits at low speed

---

board/boards/cuatro.h
board/drivers/beeper.h
board/stm32h7/board.h
board/stm32h7/peripherals.h

One of the LEDs also moved to a different pin

cuatro beeper

---

board/jungle/scripts/can_printer.py
tests/can_printer.py

- fix messages with the same addresses not showing up from each bus
- allow selecting CAN3 (obd)
- small naming cleanup

Make can_print.py work on a all busses

---

board/stm32h7/sound.h

reduces reliance on fast interrupt handling during load

Double DAC buffer

---

README.md
board/config.h
board/jungle/README.md
drivers/linux/README.md
drivers/linux/panda.c
python/__init__.py

We'll likely adjust the PID at some point as well to start from 0x1.

Switch to our new USB VID

---

Dockerfile
tests/hitl/2_health.py
tests/safety/test_chrysler.py
tests/safety/test_ford.py
tests/safety/test_gm.py
tests/safety/test_honda.py
tests/safety/test_hyundai.py
tests/safety/test_hyundai_canfd.py
tests/safety/test_nissan.py
tests/safety/test_subaru.py
tests/safety/test_subaru_preglobal.py
tests/safety/test_tesla.py
tests/safety/test_toyota.py
tests/safety/test_volkswagen_mqb.py
tests/safety/test_volkswagen_pq.py
tests/safety_replay/helpers.py

https://github.com/commaai/opendbc/pull/1711

Rename to SafetyFlags

---

board/drivers/can_common.h

Fix https://github.com/commaai/panda/pull/2157
Should do https://github.com/commaai/panda/issues/2164 soon

Rivian: fix ignition signal overlap

---

board/drivers/registers.h
board/drivers/registers_declarations.h

To aid debugging faults like commaai/openpilot#33878

Log divergent registers once

---

board/boards/cuatro.h
board/boards/dos.h
board/boards/tres.h
board/drivers/clock_source.h
board/drivers/clock_source_declarations.h

Clock source should be cleaned up a little still

Cuatro: changes for new board rev

---

.github/workflows/test.yaml
tests/misra/test_mutation.py

CI: speed up MISRA mutation job

---

.github/workflows/test.yaml
Jenkinsfile
pyproject.toml
setup.sh
test.sh
tests/hitl/3_usb.py
tests/hitl/4_can_loopback.py
tests/hitl/9_harness.py
tests/hitl/conftest.py
tests/hitl/run_parallel_tests.sh
tests/hitl/run_serial_tests.sh

Don't need all this xdist/parallel complexity now that we only test single panda-jungle combos.

simplify HITL tests

---

Jenkinsfile
python/spi.py
tests/hitl/5_spi.py

Porting over https://github.com/commaai/openpilot/pull/32645

SPI: ensure slave is in a consistent state after failed transfer

---

board/drivers/led.h

Changed LED_PWM_POWER value from 5 to 2.

Update LED_PWM_POWER definition

---

pyproject.toml
python/spi.py

Removed support for spidev2 and related transfer methods.

Remove spidev2 support from SPI implementation
